/* One continuous reading table. Card identities are shuffled once; gestures never re-deal. */
window.createTarotReading = function (bridge) {
  'use strict';
  const {esc,img,icon,go,toast,now}=bridge;
  const catalog=window.TAROT_READING_DECK,content=window.TAROT_SPREAD_CONTENT;
  const cards=Object.fromEntries(catalog.cards.map(c=>[c.id,c]));
  const spreads=Object.fromEntries(content.spreads.map(s=>[s.id,s]));
  const topics=Object.fromEntries(content.topics.map(t=>[t.id,t]));
  const KEY='tarot-reading-v3',SHUFFLE_MS=5000,CUT_MS=1200;
  const groups=[['all','基础牌阵'],['love','感情'],['work','工作'],['study','学业'],['life','生活']];
  const scenarios=()=>window.TAROT_READING_SCENARIOS||content.spreads.filter(s=>!s.legacy&&s.id!=='daily').map(s=>({id:s.id,category:s.category==='work'?'work':'all',topic:s.topic||'general',spreadId:s.id,name:s.name,description:s.bestFor,question:'',version:'1'}));
  const scenario=id=>scenarios().find(s=>s.id===id);
  const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
  const online=()=>!window.TAROT_STANDALONE&&navigator.onLine&&!!window.TAROT_AI_CONFIG?.endpoint;
  const text=(zh,en)=>document.documentElement.lang==='en'?en:zh;
  const cardCount=n=>text(n+' 张牌',n===1?'1 card':n+' cards');
  const localDay=()=>{const d=new Date(now());return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
  const cleanText=(v,n=3000)=>typeof v==='string'?v.slice(0,n):'';
  const blank=()=>({version:1,settings:{topic:'general',spreadId:'three',questionId:'own',reversals:true,contextEnabled:false},draft:null,history:[],practice:[],daily:[],ui:{view:'gallery',category:'all',guideId:'three',scenarioId:'',question:'',inputs:{},galleryY:0,resultY:0,guideReturn:'gallery'}});
  let data=blank(),storageOK=true,motion=null,revealTimer=null,selectionTimer=null,fanRAF=0,fanSave=null,detailFocus=null;
  const active=()=>data.ui.historyId?data.history.find(s=>s.id===data.ui.historyId):data.ui.dailyHistory?data.daily.find(s=>s.dailyDate===data.ui.dailyHistory):data.draft;
  const name=s=>scenario(s.scenarioId)?.name||spreads[s.spreadId].name;
  const enteredQuestion=s=>s.userQuestion===undefined?s.questionText:!!s.userQuestion;
  function validDraft(raw){
    if(!raw||!spreads[raw.spreadId]||!topics[raw.topic]||!Array.isArray(raw.pool)||raw.pool.length!==78||new Set(raw.pool.map(c=>c?.id)).size!==78||raw.pool.some(c=>!cards[c?.id]))return null;
    const count=spreads[raw.spreadId].positions.length;
    if(!Array.isArray(raw.picked)||raw.picked.length>count||new Set(raw.picked).size!==raw.picked.length||raw.picked.some(i=>!Number.isInteger(i)||i<0||i>=78))return null;
    if(raw.cutOffset!==undefined&&(!Number.isInteger(raw.cutOffset)||raw.cutOffset<0||raw.cutOffset>=78))return null;
    if(raw.dailyDate!==undefined&&(!/^\d{4}-\d{2}-\d{2}$/.test(raw.dailyDate)||raw.spreadId!=='daily'))return null;
    const revealed=Array.isArray(raw.revealed)?[...new Set(raw.revealed.filter(i=>Number.isInteger(i)&&i>=0&&i<raw.picked.length))]:[];
    const ritual=!raw.picked.length&&['shuffling','cut','cutting'].includes(raw.phase)?raw.phase:null;
    const phase=ritual||(raw.picked.length<count?'pick':revealed.length<count?'reveal':'read');
    const out={id:cleanText(raw.id,100),at:Number(raw.at)||now(),spreadId:raw.spreadId,topic:raw.topic,questionId:cleanText(raw.questionId,80)||'own',questionText:cleanText(raw.questionText),contextEnabled:raw.contextEnabled!==false,reversals:!!raw.reversals,pool:raw.pool.map(c=>({id:c.id,reversed:!!raw.reversals&&!!c.reversed})),picked:[...raw.picked],revealed,phase,active:Number.isInteger(raw.active)&&raw.active>=0&&raw.active<raw.picked.length?raw.active:0,pendingPick:null,revealPending:null,drawPage:0,motionReady:false,motionPaused:raw.motionPaused===true,motionRemaining:Number.isFinite(raw.motionRemaining)?Math.max(0,Math.min(SHUFFLE_MS,raw.motionRemaining)):undefined,fanOffset:Number.isFinite(raw.fanOffset)?Math.max(0,Math.min(15000,raw.fanOffset)):0,fanZoom:Number.isFinite(raw.fanZoom)?Math.max(.85,Math.min(1.6,raw.fanZoom)):1};
    for(const key of ['optionA','optionB','optionC'])if(typeof raw[key]==='string')out[key]=raw[key].slice(0,120);
    for(const key of ['scenarioId','sceneVersion','presetQuestion','userQuestion'])if(typeof raw[key]==='string')out[key]=cleanText(raw[key],key.includes('Question')?3000:80);
    if(raw.cutOffset!==undefined)out.cutOffset=raw.cutOffset;
    if(raw.dailyDate)out.dailyDate=raw.dailyDate;
    if(raw.ai!==undefined)out.ai=window.TarotReadingAI.clean(raw.ai);
    if(raw.answerHistory!==undefined){if(!Array.isArray(raw.answerHistory)||raw.answerHistory.length>20)throw Error('解读历史格式不正确');out.answerHistory=raw.answerHistory.map(h=>({questionText:cleanText(h.questionText),ai:window.TarotReadingAI.clean(h.ai||[])}));}
    return out;
  }
  function validate(raw){
    if(!raw||raw.version!==1||!Array.isArray(raw.history)||raw.history.length>40||!Array.isArray(raw.practice)||raw.practice.length>2000)throw Error('抽牌记录格式不正确');
    const out=blank();
    if(raw.settings&&spreads[raw.settings.spreadId]&&topics[raw.settings.topic])out.settings={...out.settings,...raw.settings,reversals:typeof raw.settings.reversals==='boolean'?raw.settings.reversals:out.settings.reversals};
    if(raw.draft){out.draft=validDraft(raw.draft);if(!out.draft)throw Error('抽牌进度损坏');}
    for(const h of raw.history){const s=validDraft(h);if(!s)throw Error('历史牌组损坏');out.history.push(s);}
    out.practice=raw.practice.filter(e=>e&&spreads[e.spreadId]&&topics[e.topic]&&Number.isInteger(e.position)&&e.position>=0&&e.position<spreads[e.spreadId].positions.length&&typeof e.correct==='boolean'&&Number.isFinite(e.at)).map(e=>({spreadId:e.spreadId,topic:e.topic,position:e.position,correct:e.correct,at:e.at}));
    const daily=raw.daily===undefined?data.daily:raw.daily;if(!Array.isArray(daily)||daily.length>366)throw Error('日签记录格式不正确');
    const dates=new Set();for(const r of daily){const s=validDraft(r);if(!s?.dailyDate||dates.has(s.dailyDate))throw Error('日签记录格式不正确');dates.add(s.dailyDate);out.daily.push(s);}
    const u=raw.ui||{view:out.draft?'table':'gallery'};out.ui={...out.ui,view:['gallery','detail','setup','table','edit'].includes(u.view)?u.view:'gallery',category:groups.some(g=>g[0]===u.category)?u.category:'all',guideId:spreads[u.guideId]?u.guideId:out.settings.spreadId,scenarioId:cleanText(u.scenarioId,80),question:cleanText(u.question),optionA:cleanText(u.optionA,120),optionB:cleanText(u.optionB,120),optionC:cleanText(u.optionC,120),galleryY:Math.max(0,Number(u.galleryY)||0),resultY:Math.max(0,Number(u.resultY)||0),guideReturn:u.guideReturn==='table'?'table':'gallery',editText:cleanText(u.editText),historyOpen:u.historyOpen===true,historyId:out.history.some(h=>h.id===u.historyId)?u.historyId:'',dailyHistory:out.daily.some(h=>h.dailyDate===u.dailyHistory)?u.dailyHistory:''};
    if(u.inputs&&typeof u.inputs==='object')for(const [key,v]of Object.entries(u.inputs).slice(0,40)){if(v&&typeof v==='object')out.ui.inputs[key]={question:cleanText(v.question),optionA:cleanText(v.optionA,120),optionB:cleanText(v.optionB,120),optionC:cleanText(v.optionC,120)};}
    if(out.ui.view==='setup')out.ui.view='detail';
    if(['table','edit'].includes(out.ui.view)&&!out.draft&&!out.ui.historyId&&!out.ui.dailyHistory)out.ui.view='gallery';
    return out;
  }
  try{const saved=localStorage.getItem(KEY);if(saved){data=validate(JSON.parse(saved));persist();}}catch(_){storageOK=false;}
  function archive(s=data.draft){
    if(!s||s.dailyDate)return true;const index=data.history.findIndex(h=>h.id===s.id);
    if(index<0&&data.history.length>=40){toast('记录已满。这组牌仍在当前牌桌，可以在抽牌记录中先导出，再删除不需要的一组。');return false;}
    const copy=structuredClone(s);if(index>=0)data.history[index]=copy;else data.history.unshift(copy);return true;
  }
  function persist(){
    if(data.draft?.dailyDate){const i=data.daily.findIndex(s=>s.dailyDate===data.draft.dailyDate);if(i>=0)data.daily[i]=structuredClone(data.draft);else if(data.daily.length<366)data.daily.unshift(structuredClone(data.draft));}
    if(data.draft?.phase==='read')archive();
    try{localStorage.setItem(KEY,JSON.stringify(data));storageOK=true;}catch(_){storageOK=false;}
  }
  function randomInt(n){const word=new Uint32Array(1),limit=Math.floor(4294967296/n)*n;do{crypto.getRandomValues(word);}while(word[0]>=limit);return word[0]%n;}
  function shuffled(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
  function cancelTimers(){if(motion){clearTimeout(motion.timer);const s=data.draft;if(s?.id===motion.id)s.motionRemaining=Math.max(0,motion.remaining-(performance.now()-motion.started));motion=null;}clearTimeout(selectionTimer);selectionTimer=null;}
  function redraw(y=0,page='reading'){go(page);requestAnimationFrame(()=>{window.scrollTo(0,y);mountFan();requestAnimationFrame(()=>document.body.classList.remove('nav-away'));});}
  function leaveTable(){cancelTimers();data.ui.view='gallery';data.ui.historyId='';data.ui.dailyHistory='';persist();redraw(data.ui.galleryY);}
  function ensureMotion(){const s=data.draft;if(!s||data.ui.view!=='table'||s.motionPaused||motion||!['shuffling','cutting'].includes(s.phase))return;const remaining=reduced()?0:s.motionRemaining??(s.phase==='shuffling'?SHUFFLE_MS:CUT_MS);const job={id:s.id,remaining,started:performance.now(),timer:null};motion=job;job.timer=setTimeout(()=>{if(motion!==job)return;motion=null;advanceMotion();},remaining);}
  function advanceMotion(){const s=data.draft;if(!s||!['shuffling','cutting'].includes(s.phase))return;cancelTimers();s.phase=s.phase==='shuffling'?'cut':'pick';s.motionPaused=false;delete s.motionRemaining;persist();if(data.ui.view==='table')redraw();}
  function pauseMotion(){const s=data.draft;if(!s)return;if(s.motionPaused)s.motionPaused=false;else{cancelTimers();s.motionPaused=true;}persist();const stage=document.querySelector('[data-motion-stage]');stage?.classList.toggle('motion-paused',s.motionPaused);const button=document.querySelector('[data-reading=motion-pause]');if(button)button.textContent=s.motionPaused?text('继续洗牌','Resume shuffling'):text('暂停洗牌','Pause shuffling');const status=stage?.querySelector('[role=status]');if(status)status.textContent=s.motionPaused?text('洗牌已暂停','Shuffling paused'):s.phase==='shuffling'?text('正在洗牌…','Shuffling…'):text('牌叠正在合拢…','Gathering the deck…');if(!s.motionPaused)ensureMotion();}
  function replayMotion(){const s=data.draft;if(!s||!['shuffling','cutting'].includes(s.phase))return;cancelTimers();s.motionPaused=false;s.motionRemaining=s.phase==='shuffling'?SHUFFLE_MS:CUT_MS;persist();redraw(window.scrollY);}
  function prepare(daily=false){
    if(!daily&&data.ui.guideId==='yes-no'&&!data.ui.question.trim()){toast('请先写下想问的具体事情。');document.querySelector('[data-reading-question]')?.focus();return;}
    if(data.draft&&!archive()){data.ui.view='gallery';data.ui.historyOpen=true;persist();redraw();requestAnimationFrame(()=>document.getElementById('reading-history')?.scrollIntoView({block:'start'}));return;}cancelTimers();
    const sc=daily?null:scenario(data.ui.scenarioId),d=spreads[daily?'daily':data.ui.guideId];
    const topic=daily?'general':sc?.topic||d.topic||'general',userQuestion=daily?'':data.ui.question.trim(),preset=daily?'':sc?.question||'';
    try{data.draft={id:'reading-'+Date.now()+'-'+randomInt(1000000000),at:now(),spreadId:d.id,topic,questionId:'own',questionText:userQuestion||preset,userQuestion,presetQuestion:preset,scenarioId:sc?.id||'',sceneVersion:sc?.version||'1',contextEnabled:topic!=='general',reversals:true,pool:shuffled(catalog.cards.map(c=>({id:c.id,reversed:randomInt(2)===1}))),picked:[],revealed:[],phase:'shuffling',active:0,motionPaused:false,fanOffset:0,fanZoom:1,pendingPick:null,revealPending:null,drawPage:0,...(['decision-five','three-options'].includes(d.id)?{optionA:data.ui.optionA||'',optionB:data.ui.optionB||'',...(d.id==='three-options'?{optionC:data.ui.optionC||''}:{})}:{}),...(daily?{dailyDate:localDay()}:{})};}catch(_){toast('当前浏览器无法随机洗牌，请换用支持的浏览器。');return;}
    data.settings={...data.settings,spreadId:d.id,topic,reversals:true,contextEnabled:topic!=='general'};data.ui.historyId='';data.ui.dailyHistory='';data.ui.view='table';persist();redraw();
  }
  function openDaily(){const saved=data.daily.find(s=>s.dailyDate===localDay());if(saved){cancelTimers();if(data.draft&&!archive())return;data.draft=structuredClone(saved);data.ui.historyId='';data.ui.dailyHistory='';data.ui.view='table';persist();redraw();}else prepare(true);}
  function cut(offset){const s=data.draft;if(!s||s.phase!=='cut'||![0,26,52].includes(offset))return;s.pool=[...s.pool.slice(offset),...s.pool.slice(0,offset)];s.cutOffset=offset;s.phase='cutting';s.motionPaused=false;delete s.motionRemaining;persist();redraw();}
  function spreadThumb(d){return `<span class="spread-thumb thumb-${esc(d.layout)} count-${d.positions.length}" aria-hidden="true">${d.positions.map(()=>'<i></i>').join('')}</span>`;}
  function scenarioOrder(a,b){
    const cardsA=spreads[a.spreadId].positions.length,cardsB=spreads[b.spreadId].positions.length;
    return cardsA-cardsB||scenarios().indexOf(a)-scenarios().indexOf(b);
  }
  function questionLabel(s){return s.questionText||text(s.spreadId==='one'?'这张牌给你的提醒':s.spreadId==='open-three'?'三张牌的整体提示':'按牌阵给你一些一般提示',s.spreadId==='one'?'A reminder from this card':s.spreadId==='open-three'?'General guidance from three cards':'General guidance from this spread');}
  function dailyTile(){const s=data.daily.find(x=>x.dailyDate===localDay());return `<button class="daily-tile" data-reading="daily"><span class="daily-orbit" aria-hidden="true">☾</span><span><small>${esc(localDay())}</small><strong>今日塔罗</strong><span>${s?.phase==='read'?'看今天的牌':s?'继续今天的日签':'抽今天的牌'}</span></span>${icon('arrow')}</button>`;}
  function historySection(){return `<section class="reading-history section" id="reading-history"><details ${data.ui.historyOpen?'open':''}><summary>我的抽牌记录 <span>${data.history.length} / 40</span></summary>${data.history.length?'<div class="reading-history-actions"><button class="secondary" data-action="export">导出全部记录</button><p>记录满了，可以先导出备份，再删除不需要的一组。</p></div>':''}${data.history.map(s=>`<div class="reading-history-row"><button class="practice-row" data-reading="history" data-value="${esc(s.id)}"><span><strong>${esc(name(s))}</strong><p ${enteredQuestion(s)?'data-i18n-ignore':''}>${esc(questionLabel(s))}</p><small>${new Date(s.at).toLocaleDateString(document.documentElement.lang==='en'?'en':'zh-CN')} · <span>${s.phase==='read'?'已完成':'尚未完成'}</span></small></span>${icon('arrow')}</button><button class="linkbtn" data-reading="delete-history" data-value="${esc(s.id)}" aria-label="删除这组记录">删除</button></div>`).join('')||'<p>完成的牌组会自动保存在这里。</p>'}</details><details><summary>往日的日签 <span>${data.daily.length}</span></summary>${data.daily.map(s=>`<button class="practice-row" data-reading="daily-history" data-value="${esc(s.dailyDate)}"><span>${esc(s.dailyDate)}</span>${icon('arrow')}</button>`).join('')||'<p>每天的牌会留在这里。</p>'}</details><dialog class="reading-detail-dialog reading-delete-dialog" data-reading-delete-dialog aria-labelledby="reading-delete-title"></dialog></section>`;}
  function confirmHistoryDeletion(id){const s=data.history.find(s=>s.id===id),dialog=document.querySelector('[data-reading-delete-dialog]');if(!s||!dialog)return;dialog.innerHTML=`<h2 id="reading-delete-title">删除这组记录？</h2><p><strong>${esc(name(s))}</strong></p><p ${enteredQuestion(s)?'data-i18n-ignore':''}>${esc(questionLabel(s))}</p><p>只删除这组抽牌记录。学习进度和其他记录会保留。</p>${data.draft?.id===id?'<p>当前牌桌也是这一组，删除后会一起关闭。</p>':''}<p>删除后不能直接找回。你可以先导出备份。</p><div class="buttonstack"><button class="secondary" data-action="export">先导出全部记录</button><button class="primary" data-reading="confirm-delete-history" data-value="${esc(id)}">删除这组记录</button><button class="linkbtn" data-reading="cancel-delete-history">保留记录</button></div>`;dialog.showModal();}

  function gallery(){
    const [category,label]=groups.find(g=>g[0]===data.ui.category)||groups[0];
    const list=scenarios().filter(s=>s.category===category&&spreads[s.spreadId]).sort(scenarioOrder);
    return `<div class="reading-v2 reading-directory"><header class="pagehead"><span class="eyebrow">YOUR READING TABLE</span><h1>这次，想问什么？</h1><p>选一个问题，或用基础牌阵自由抽牌。</p></header>${dailyTile()}${data.draft?`<button class="practice-row reading-resume" data-reading="resume"><span><strong>${data.draft.phase==='read'?'回到刚才的牌':'继续上次抽牌'}</strong><p>${esc(name(data.draft))} · <span>已选</span> ${data.draft.picked.length} / ${spreads[data.draft.spreadId].positions.length}</p></span>${icon('arrow')}</button>`:''}<nav class="reading-theme-nav" aria-label="选择问题分类">${groups.map(([id,itemLabel])=>`<button class="chip ${category===id?'active':''}" data-reading="category" data-value="${id}">${itemLabel}</button>`).join('')}</nav><div data-reading-results><section class="reading-theme" id="reading-theme-${category}"><div class="sectionhead"><h2>${label}</h2><span class="muted">${list.length}</span></div><div class="reading-scenario-list">${list.map(sc=>{const d=spreads[sc.spreadId];return `<button class="reading-spread-choice" data-reading="guide" data-value="${d.id}" data-scenario="${esc(sc.id)}">${spreadThumb(d)}<span class="spread-choice-copy"><strong>${esc(sc.name)}</strong><p>${esc(sc.description)}</p><small>${cardCount(d.positions.length)}</small></span>${icon('arrow')}</button>`;}).join('')}</div></section></div>${historySection()}</div>`;
  }
  function introDiagram(d){return `<div class="reading-board layout-${esc(d.layout)} count-${d.positions.length} phase-guide reading-static-diagram" aria-label="${esc(d.name)}">${d.positions.map((p,i)=>`<div class="reading-slot slot-${i+1}"><span class="reading-card"><span class="reading-back reading-placeholder"><b>${i+1}</b></span></span><span class="reading-label">${esc(p.label)}</span></div>`).join('')}</div>`;}
  function inputKey(){return data.ui.scenarioId||data.ui.guideId;}
  function saveInputs(){data.ui.inputs[inputKey()]={question:data.ui.question,optionA:data.ui.optionA||'',optionB:data.ui.optionB||'',optionC:data.ui.optionC||''};persist();}
  function openGuide(id,sceneId='',fromResult=false){if(!spreads[id])return;cancelTimers();data.ui.guideReturn=fromResult?'table':'gallery';if(fromResult)data.ui.resultY=window.scrollY;else data.ui.galleryY=window.scrollY;data.ui.guideId=id;data.ui.scenarioId=sceneId;const input=data.ui.inputs[inputKey()];if(input)Object.assign(data.ui,input);else if(!fromResult){data.ui.question='';data.ui.optionA='';data.ui.optionB='';data.ui.optionC='';}data.ui.view='detail';persist();redraw(0,'spread-guide');}
  function renderGuide(){
    const d=spreads[data.ui.guideId],sc=scenario(data.ui.scenarioId),readOnly=data.ui.guideReturn==='table',s=active();
    return `<article class="reading-v2 compact-spread-guide"><header class="reading-header"><button class="iconbtn" data-reading="guide-back" aria-label="返回">${icon('back')}</button><div><small>${cardCount(d.positions.length)}</small><h1>${esc(readOnly&&s?name(s):sc?.name||d.name)}</h1></div></header><section class="reading-guide-overview"><p class="reading-purpose">${esc(sc?.description||d.bestFor)}</p><h2>每张牌代表什么</h2><div class="reading-guide-diagram">${introDiagram(d)}</div><ol class="reading-position-list">${d.positions.map((p,i)=>`<li><span>${i+1}</span><div><strong>${esc(p.label)}</strong><p>${esc(p.question)}</p></div></li>`).join('')}</ol></section>${readOnly?'':`<section class="reading-question-setup">${sc?.question?`<div class="reading-preset"><small>这次的问题</small><p>${esc(sc.question)}</p></div>`:''}<label class="question-field"><span>${d.id==='yes-no'?'你想知道哪件事能不能发生？':'想问得更具体？可以写在这里。'}</span><textarea data-reading-question data-i18n-ignore maxlength="3000" rows="3" placeholder="${esc(text('例如：接下来一个月，我的求职有机会顺利吗？','For example: Could my job search go well over the next month?'))}">${esc(data.ui.question)}</textarea><small>${d.id==='yes-no'?'写清楚一件事，再开始抽牌。':sc?.question?'不填写，就按上面的问题解读。':d.id==='one'?'不填写，就看这张牌给你的提醒。':'不填写，就按牌阵给你一些一般提示。'}</small></label>${['decision-five','three-options'].includes(d.id)?`<div class="reading-options">${['A','B',...(d.id==='three-options'?['C']:[])].map(k=>`<label><span>${k} <span>是什么？（可选）</span></span><input data-reading-option="option${k}" data-i18n-ignore maxlength="120" value="${esc(data.ui['option'+k]||'')}"></label>`).join('')}</div>`:''}<button class="primary wide" data-reading="start">开始洗牌 ${icon('arrow')}</button></section>`}<details class="reading-source"><summary>牌阵说明与来源</summary><p>${esc(d.description||d.summary||d.bestFor)}</p>${d.legacy?'<p>这是旧版记录使用的牌阵。</p>':''}${d.source?`<p>${esc(d.source.note||'')}</p><a href="${esc(d.source.url)}" target="_blank" rel="noopener noreferrer">${esc(d.source.title)}</a>`:''}</details></article>`;
  }
  function header(s){return `<header class="reading-header"><button class="iconbtn" data-reading="pause" aria-label="返回抽牌首页">${icon('back')}</button><div><small>${s.dailyDate?esc(s.dailyDate):text('你的牌桌','Your reading table')}</small><h1>${esc(name(s))}</h1></div></header>`;}
  function ritual(s){
    const phase=s.phase,steps=['洗牌','切牌','选牌','揭牌'],n={shuffling:0,cut:1,cutting:1,pick:2,reveal:3}[phase];
    const progress=`<ol class="ritual-progress">${steps.map((label,i)=>`<li class="${i===n?'current':i<n?'done':''}"><span>${i+1}</span>${label}</li>`).join('')}</ol>`;
    if(!['shuffling','cut','cutting'].includes(phase))return progress;
    const shuffle=phase==='shuffling',cutting=phase==='cutting';
    return `${progress}<section class="ritual-table ritual-space ${shuffle?'reading-shuffle':'reading-cut'} ${cutting?'is-cutting':''} ${s.motionPaused?'motion-paused':''}" data-motion-stage="${phase}" style="--shuffle-duration:${SHUFFLE_MS}ms;--motion-elapsed:${s.motionRemaining===undefined?0:Math.max(0,(shuffle?SHUFFLE_MS:CUT_MS)-s.motionRemaining)}ms"><div class="ritual-glow" aria-hidden="true"></div><h2>${shuffle?'想一想，这次最想弄清什么。':cutting?'正在收齐牌组':'点一叠，把它放到最上面。'}</h2>${shuffle?`<div class="shuffle-pack ritual-pack" aria-hidden="true">${Array.from({length:18},(_,i)=>`<div class="reading-back" style="--card-index:${i};--fan-x:${(i-8.5)*10};--fan-y:${Math.abs(i-8.5)*3-15};--fan-r:${(i-8.5)*3}deg;--scatter-x:${((i*7)%6-2.5)*35};--scatter-y:${(Math.floor((i*7)%18/6)-1)*74};--scatter-r:${(i*47)%240-120}deg;--mix-x:${((i*11+5)%6-2.5)*35};--mix-y:${(Math.floor((i*11+5)%18/6)-1)*74};--mix-r:${(i*73)%260-130}deg"></div>`).join('')}</div><div class="shuffle-stage-label" aria-hidden="true"><span>摊开牌组</span><span>打散混洗</span><span>收拢牌叠</span></div>`:`<div class="cut-piles">${[0,26,52].map((offset,i)=>`<button class="cut-pile ${s.cutOffset===offset?'selected':''}" data-reading="cut" data-index="${offset}" style="--pile-index:${i}" ${cutting?'disabled':''} aria-label="${['选择左侧牌叠','选择中间牌叠','选择右侧牌叠'][i]}">${[0,1,2,3].map(j=>`<span class="reading-back" style="--layer:${j}" aria-hidden="true"></span>`).join('')}<small>${['左侧','中间','右侧'][i]}</small></button>`).join('')}</div>`}<p role="status">${s.motionPaused?'洗牌已暂停':shuffle?'正在洗牌…':cutting?'牌叠正在合拢…':'按自己的感觉选就好。'}</p></section>`;
  }
  function tray(s){const d=spreads[s.spreadId];return `<div class="reading-board selection-board layout-${esc(d.layout)} count-${d.positions.length} phase-pick" aria-label="已选牌与牌位">${d.positions.map((p,i)=>`<div class="reading-slot slot-${i+1} ${s.picked[i]!==undefined?'filled':''} ${s.picked.length===i?'current':''}"><span class="reading-card" aria-hidden="true">${s.picked[i]!==undefined?'<span class="reading-back"></span>':`<span class="reading-back reading-placeholder"><b>${i+1}</b></span>`}</span><span class="reading-label">${i+1} · ${esc(p.label)}</span></div>`).join('')}</div>`;}
  function pickTable(s){const d=spreads[s.spreadId],zoomed=s.fanZoom>1.08;return `<section class="ritual-selection reading-fan-table"><div class="ritual-selection-heading"><h2><span>选第</span> ${s.picked.length+1} <span>张</span> · ${esc(d.positions[s.picked.length].label)}</h2><span class="ritual-count">${s.picked.length} / ${d.positions.length}</span></div><p>左右滑动，点一张喜欢的牌。</p><div data-selected-tray>${tray(s)}</div><div class="fan-toolbar"><span>需要看编号时，可以双指放大。</span><div><button class="iconbtn" data-reading="fan-out" aria-label="缩小">−</button><button class="iconbtn" data-reading="fan-in" aria-label="放大">＋</button></div></div><div class="reading-fan-viewport ${zoomed?'fan-is-zoomed':''}" data-fan-viewport style="--fan-scale:${s.fanZoom}" role="group" aria-label="整副 78 张牌"><div class="reading-fan-track">${s.pool.map((_,i)=>`<button class="reading-fan-card ${s.picked.includes(i)?'was-picked':''}" data-deck-card data-reading="pick" data-index="${i}" ${s.picked.includes(i)?'disabled':''} aria-label="${esc(text('牌背 '+(i+1),'Card back '+(i+1)))}"><span class="fan-number" aria-hidden="true">${i+1}</span><span class="reading-back" aria-hidden="true"></span><span class="deck-picked-mark" aria-hidden="true">${s.picked.includes(i)?'✓':''}</span></button>`).join('')}</div></div><div class="fan-footer"><span data-fan-range aria-hidden="true"></span><button class="linkbtn" data-reading="undo" ${s.picked.length?'':'disabled'}>撤回刚选的一张</button></div></section>`;}
  let fanElement=null,gesture=null,suppressPickUntil=0,pinch=null;
  function paintFan(){fanRAF=0;const el=fanElement;if(!el?.isConnected)return;const center=el.scrollLeft+el.clientWidth/2;let closest=0,dist=Infinity;el.querySelectorAll('[data-deck-card]').forEach(card=>{const x=card.offsetLeft+card.offsetWidth/2-center,unit=x/(card.offsetWidth+8),angle=Math.max(-30,Math.min(30,unit*8)),y=Math.min(80,unit*unit*7);card.style.transform=`translateY(${y}px) rotate(${angle}deg)`;if(Math.abs(x)<dist){dist=Math.abs(x);closest=Number(card.dataset.index);}});const label=document.querySelector('[data-fan-range]');if(label)label.textContent=(closest+1)+' / 78';}
  function mountFan(){const el=document.querySelector('[data-fan-viewport]'),s=data.draft;if(!el||!s||el===fanElement)return;fanElement=el;el.scrollLeft=s.fanOffset||0;paintFan();el.addEventListener('scroll',()=>{if(!fanRAF)fanRAF=requestAnimationFrame(paintFan);s.fanOffset=el.scrollLeft;clearTimeout(fanSave);fanSave=setTimeout(persist,180);},{passive:true});}
  function zoomFan(factor){const el=fanElement,s=data.draft;if(!el||s?.phase!=='pick')return;const old=s.fanZoom,next=Math.max(.85,Math.min(1.6,old*factor));if(next===old)return;const center=el.scrollLeft+el.clientWidth/2;s.fanZoom=next;el.style.setProperty('--fan-scale',String(next));el.classList.toggle('fan-is-zoomed',next>1.08);el.scrollLeft=Math.max(0,center*next/old-el.clientWidth/2);s.fanOffset=el.scrollLeft;suppressPickUntil=Date.now()+300;paintFan();persist();}
  // A fresh tap is its own gesture. Restored/native scroll events must not cancel it;
  // only movement, cancellation or a pinch suppresses that gesture's generated click.
  document.addEventListener('pointerdown',e=>{if(!e.target.closest?.('[data-fan-viewport]'))return;gesture={x:e.clientX,y:e.clientY,moving:!!pinch};suppressPickUntil=pinch?Date.now()+500:0;},{passive:true});
  document.addEventListener('pointermove',e=>{if(gesture&&Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)>8){gesture.moving=true;suppressPickUntil=Date.now()+300;}},{passive:true});
  document.addEventListener('pointerup',()=>{if(gesture?.moving)suppressPickUntil=Date.now()+300;gesture=null;},{passive:true});
  document.addEventListener('pointercancel',()=>{if(gesture)suppressPickUntil=Date.now()+300;gesture=null;},{passive:true});
  document.addEventListener('touchstart',e=>{if(e.touches.length===2&&e.target.closest?.('[data-fan-viewport]')){pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);suppressPickUntil=Date.now()+500;}},{passive:true});
  document.addEventListener('touchmove',e=>{if(pinch&&e.touches.length===2&&e.target.closest?.('[data-fan-viewport]')){e.preventDefault();const distance=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);zoomFan(distance/pinch);pinch=distance;}},{passive:false});
  document.addEventListener('touchend',e=>{if(pinch&&e.touches.length<2){pinch=null;suppressPickUntil=Date.now()+500;}},{passive:true});
  function updatePick(s){const h=document.querySelector('.ritual-selection-heading');if(h)h.innerHTML=`<h2><span>选第</span> ${s.picked.length+1} <span>张</span> · ${esc(spreads[s.spreadId].positions[s.picked.length]?.label||'')}</h2><span class="ritual-count">${s.picked.length} / ${spreads[s.spreadId].positions.length}</span>`;document.querySelectorAll('.selection-board .reading-slot').forEach((slot,index)=>{const filled=s.picked[index]!==undefined;slot.classList.toggle('current',s.picked.length===index);if(filled!==slot.classList.contains('filled')){slot.classList.toggle('filled',filled);slot.querySelector('.reading-card').innerHTML=filled?'<span class="reading-back"></span>':`<span class="reading-back reading-placeholder"><b>${index+1}</b></span>`;}});document.querySelectorAll('[data-deck-card]').forEach(el=>{const used=s.picked.includes(Number(el.dataset.index));el.disabled=used;el.classList.toggle('was-picked',used);el.querySelector('.deck-picked-mark').textContent=used?'✓':'';});const undo=document.querySelector('[data-reading="undo"]');if(undo)undo.disabled=!s.picked.length;}
  function pick(i,button){const s=data.draft;if(!s||s.phase!=='pick'||Date.now()<suppressPickUntil||!Number.isInteger(i)||i<0||i>=78||s.picked.includes(i))return;const source=button.getBoundingClientRect();s.picked.push(i);if(s.picked.length===spreads[s.spreadId].positions.length)s.phase='reveal';persist();updatePick(s);const target=document.querySelectorAll('.selection-board .reading-card')[s.picked.length-1]?.getBoundingClientRect();if(!reduced()&&target){const fly=document.createElement('span');fly.className='reading-back fan-flying-card';Object.assign(fly.style,{left:source.left+'px',top:source.top+'px',width:source.width+'px',height:source.height+'px'});document.body.append(fly);const animation=fly.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${target.left-source.left}px,${target.top-source.top}px) scale(${target.width/source.width},${target.height/source.height})`,opacity:.8}],{duration:400,easing:'cubic-bezier(.2,.7,.2,1)',fill:'forwards'});animation.onfinish=()=>fly.remove();}
    if(s.phase==='reveal'){const id=s.id;selectionTimer=setTimeout(()=>{selectionTimer=null;if(data.draft?.id===id&&data.ui.view==='table')redraw();},reduced()?0:420);}
  }
  function undo(){const s=data.draft;if(!s||!['pick','reveal'].includes(s.phase)||s.revealed.length||!s.picked.length)return;cancelTimers();s.picked.pop();s.phase='pick';persist();if(document.querySelector('[data-fan-viewport]'))updatePick(s);else redraw();}
  function revealTable(s){const d=spreads[s.spreadId],revealing=s.revealed.length===s.picked.length;return `<section class="ritual-table reveal-group ${revealing?'is-revealing-group':''}"><span class="reveal-aura" aria-hidden="true"></span><h2>${s.dailyDate?'揭开今天的牌':'选好了，一起揭牌并解读。'}</h2><div class="reading-board reveal-group-cards layout-${esc(d.layout)} count-${s.picked.length}">${s.picked.map((n,i)=>{const c=s.pool[n];return `<figure class="reading-slot slot-${i+1}" style="--reveal-order:${i}"><div class="reveal-group-face ${c.reversed?'is-reversed':''}">${revealing?img(c.id):'<span class="reading-back"></span>'}${revealing?'<span class="group-flip-back reading-back" aria-hidden="true"></span>':''}</div><figcaption>${i+1} · ${esc(d.positions[i].label)}</figcaption></figure>`;}).join('')}</div>${revealing?'<p role="status">牌面正在展开…</p>':`<div class="buttonstack"><button class="primary wide" data-reading="reveal">${s.dailyDate?'揭开今天的牌':'揭牌并解读'} ${icon('arrow')}</button>${!s.dailyDate?`<p class="reading-disclosure">${online()?'会自动连接解读服务，回答这次的问题。':'这次会先揭开牌面；联网服务恢复后可自动解读。'}</p>`:''}<button class="linkbtn" data-reading="undo">撤回刚选的一张</button></div>`}</section>`;}
  function saveAnswer(id,answer,requestContext){for(const s of [data.draft,...data.history,...data.daily])if(s?.id===id&&(!requestContext||JSON.stringify(window.TarotReadingAI.buildRequest(s,answer.language))===requestContext))s.ai=[...(s.ai||[]).filter(x=>x.language!==answer.language),answer];persist();}
  function requestAI(s){if(s?.phase==='read')window.TarotReadingAI?.request(s,saveAnswer,()=>data.ui.view==='table'?active():null);}
  function revealAll(withAI=false){const s=data.draft;if(!s||s.phase!=='reveal'||s.revealed.length||s.picked.length!==spreads[s.spreadId].positions.length)return;s.revealed=s.picked.map((_,i)=>i);s.revealPending=null;persist();redraw();const id=s.id;const finish=()=>{revealTimer=null;if(data.draft?.id!==id)return;s.phase='read';archive(s);persist();if(data.ui.view==='table'){redraw();if(withAI&&!s.dailyDate)requestAI(s);}};if(reduced())finish();else revealTimer=setTimeout(finish,1100);}
  function resultCards(s){const d=spreads[s.spreadId];return `<div class="reading-board reading-result-cards layout-${esc(d.layout)} count-${s.picked.length} phase-read" aria-label="这次抽到的牌">${s.picked.map((n,i)=>{const c=s.pool[n];return `<button class="reading-result-card reading-slot slot-${i+1}" data-reading="card" data-index="${i}" aria-label="${esc(cards[c.id].name)} ${c.reversed?'逆位':'正位'}"><span class="reading-card ${c.reversed?'is-reversed':''}">${img(c.id)}</span><span class="reading-label">${i+1} · ${esc(d.positions[i].label)}</span><small>${esc(cards[c.id].name)} · <span>${c.reversed?'逆位':'正位'}</span></small></button>`;}).join('')}</div>`;}
  function detail(s,i){const draw=s.pool[s.picked[i]],c=cards[draw.id],p=spreads[s.spreadId].positions[i];return `<button class="iconbtn reading-detail-close" data-reading="close-reference" aria-label="返回刚才的位置">${icon('back')}</button><div class="reading-detail-portrait"><button data-reading="detail-zoom" aria-label="放大牌面">${img(c.id,draw.reversed?'class="reversed-img"':'')}</button><div><h2 id="reading-detail-title">${esc(c.name)}</h2><p>${draw.reversed?'逆位':'正位'} · ${esc(p.label)}</p></div></div><section><h3>这张牌的意思</h3><p>${esc(c.core)}</p><p>${esc(draw.reversed?c.reversed:c.upright)}</p></section><section><h3>画面里的线索</h3><p>${esc(c.observation)}</p></section><section><h3>${draw.reversed?'正位':'逆位'}</h3><p>${esc(draw.reversed?c.upright:c.reversed)}</p></section><section><h3>这张牌在这里回答什么</h3><p>${esc(p.question)}</p></section><button class="secondary wide" data-reading="close-reference">返回刚才的位置</button>`;}
  function openDetail(i,button){const s=active();if(!s||s.phase!=='read'||s.picked[i]===undefined)return;const dialog=document.querySelector('[data-reading-dialog]');if(!dialog)return;detailFocus=button;dialog.innerHTML=detail(s,i);dialog.showModal();dialog.onclick=e=>{if(e.target===dialog)closeDetail();};}
  function closeDetail(){document.querySelector('[data-reading-dialog]')?.close();detailFocus?.focus({preventScroll:true});}
  function report(s){return `<section class="reading-result-question"><small>${s.questionText?'这次的问题':s.spreadId==='open-three'?'三张牌的整体提示':'这次的提示'}</small><p ${enteredQuestion(s)?'data-i18n-ignore':''}>${esc(questionLabel(s))}</p></section>${resultCards(s)}<div data-reading-completion>${window.TarotReadingAI?.render(s)||'<p>现在可以先看牌义。</p>'}</div><div class="reading-result-tools"><button class="secondary" data-reading="edit-question">补充或修改问题</button><button class="linkbtn" data-reading="result-guide">看本次牌阵说明</button></div><details class="reading-offline-reference"><summary>看单张牌的意思</summary><p>这里是各张牌的含义，不会分析你写的问题。</p>${s.picked.map((n,i)=>`<button class="practice-row" data-reading="card" data-index="${i}"><span>${i+1} · ${esc(spreads[s.spreadId].positions[i].label)}</span><strong>${esc(cards[s.pool[n].id].name)}</strong>${icon('arrow')}</button>`).join('')}</details>${s.answerHistory?.length?`<details class="reading-answer-history"><summary>之前的回答</summary>${s.answerHistory.map(h=>`<section><strong data-i18n-ignore>${esc(h.questionText)}</strong>${(h.ai||[]).map(a=>`<p class="reading-previous-answer" data-i18n-ignore>${esc(a.text)}</p>`).join('')}</section>`).join('')}</details>`:''}<p class="reading-save-status" role="status">${storageOK?'已保存在本机':'这次还没保存成功。请先留在这里，再试一次。'}</p>${!storageOK?'<button class="secondary" data-reading="save-again">再试一次</button>':''}<div class="reading-result-return"><button class="primary wide" data-reading="pause">返回抽牌首页 ${icon('arrow')}</button></div><dialog class="reading-detail-dialog" data-reading-dialog aria-labelledby="reading-detail-title"></dialog>`;}
  function editQuestion(s){const canReread=online()&&!s.dailyDate;return `<header class="reading-header"><button class="iconbtn" data-reading="edit-back" aria-label="返回解读">${icon('back')}</button><h1>补充或修改问题</h1></header><section class="reading-edit-question"><p>补充这件事的情况，再用原来的牌解读。之前的回答会保留。</p><label class="question-field"><span>这次的问题</span><textarea data-reading-edit data-i18n-ignore maxlength="3000" rows="5">${esc(data.ui.editText)}</textarea></label><p>${esc(spreads[s.spreadId].bestFor)}</p><p>如果想问另一件事，可以返回首页重新选牌阵。</p><button class="primary wide" data-reading="save-question">${canReread?'保存并重新解读':'保存问题'}</button><button class="linkbtn" data-reading="edit-back">返回解读</button></section>`;}
  function dailyResult(s){
    const draw=s.pool[s.picked[0]],c=cards[draw.id],orientation=draw.reversed?'逆位':'正位';
    const [year,month,day]=s.dailyDate.split('-'),date=new Date(Number(year),Number(month)-1,Number(day),12);
    const weekday=['星期日','星期一','星期二','星期三','星期四','星期五','星期六'][date.getDay()];
    const guidance=window.TAROT_DAILY_GUIDANCE[c.id][draw.reversed?'reversed':'upright'];
    return `<article class="daily-result daily-almanac" data-daily-date="${esc(s.dailyDate)}" aria-labelledby="daily-title">
      <header class="daily-masthead"><div class="daily-masthead-copy"><span class="daily-edition">TAROT POCKET</span><h2 id="daily-title">塔罗日签</h2><span class="daily-dedication">一日一签，留一点时间给自己。</span></div><time class="daily-calendar" datetime="${esc(s.dailyDate)}"><span class="daily-month" data-i18n-ignore>${year} / ${month}</span><strong data-i18n-ignore>${day}</strong><span>${weekday}</span></time><span class="daily-celestial" aria-hidden="true">☾ · ✦</span></header>
      <div class="daily-paper"><div class="daily-card-and-signs"><figure class="daily-portrait"><button class="daily-cover" data-action="zoom" data-id="${esc(c.id)}" data-face="${draw.reversed?'reversed':'upright'}" aria-label="放大牌面">${img(c.id,draw.reversed?'class="reversed-img"':'')}<span class="daily-zoom" aria-hidden="true">${icon('zoom')}</span></button><figcaption><h3>${esc(c.name)}</h3><span>${orientation}</span></figcaption></figure><div class="daily-signs"><section class="daily-sign daily-do"><h3><span>宜</span></h3><p>${esc(guidance.do)}</p></section><section class="daily-sign daily-avoid"><h3><span>忌</span></h3><p>${esc(guidance.avoid)}</p></section><small>顺着牌意，照顾今天。</small></div></div>
      <section class="daily-message"><h3>今天，把注意力放在这里。</h3><p class="daily-core">${esc(c.core)}</p></section>
      <section class="daily-advice"><h3>一件可以尝试的事</h3><p>${esc(draw.reversed?c.reversed:c.upright)}</p><small>选择其中一件与你实际生活有关的小事，今晚再看看发生了什么。</small></section>
      <details class="daily-reference"><summary>查看这张牌的依据</summary><p>${esc(c.observation)}</p><p class="daily-provenance">宜忌是这张牌的生活提醒，不是传统黄历的吉凶择日。</p><button class="linkbtn" data-reading="card" data-index="0">查看单牌完整释义</button></details>
      <footer class="daily-footer"><p><span aria-hidden="true">✦</span><span>今天的日签已经保存。重新打开，仍是这张牌。</span></p><button class="primary wide" data-reading="finish">返回抽牌首页 ${icon('arrow')}</button></footer></div></article>`;
  }
  function render(){if(data.ui.view==='detail')return renderGuide();if(data.ui.view==='gallery')return gallery();const s=active();if(!s)return gallery();if(data.ui.view==='edit')return `<div class="reading-v2">${editQuestion(s)}</div>`;if(s.dailyDate&&s.phase==='read')return `<div class="reading-v2">${header(s)}${dailyResult(s)}<dialog class="reading-detail-dialog" data-reading-dialog aria-labelledby="reading-detail-title"></dialog></div>`;if(s===data.draft)ensureMotion();requestAnimationFrame(mountFan);return `<div class="reading-v2 reading-table phase-${s.phase}">${header(s)}${s.phase==='read'?report(s):`${s.questionText?`<p class="reading-table-question" ${enteredQuestion(s)?'data-i18n-ignore':''}>${esc(s.questionText)}</p>`:''}${ritual(s)}${s.phase==='pick'?`<div data-ritual-pick>${pickTable(s)}</div>`:s.phase==='reveal'?revealTable(s):''}`}</div>`;}
  function dashboard(){return `<section class="section"><div class="sectionhead"><h2>我的牌桌</h2><span>${data.history.length} <span>组记录</span></span></div><button class="secondary wide" data-reading="gallery">打开抽牌与记录</button></section>`;}
  function learningHub(){return `<section class="section"><h2>认识牌阵</h2>${content.spreads.filter(s=>!s.legacy).map(s=>`<button class="practice-row" data-reading="guide" data-value="${s.id}"><strong>${esc(s.name)}</strong><span>${cardCount(s.positions.length)}</span>${icon('arrow')}</button>`).join('')}</section>`;}
  document.addEventListener('input',e=>{const el=e.target;if(el.matches('[data-reading-question]')&&data.ui.view==='detail'){data.ui.question=el.value.slice(0,3000);saveInputs();}if(el.matches('[data-reading-option]')&&data.ui.view==='detail'&&['optionA','optionB','optionC'].includes(el.dataset.readingOption)){data.ui[el.dataset.readingOption]=el.value.slice(0,120);saveInputs();}if(el.matches('[data-reading-edit]')&&data.ui.view==='edit'){data.ui.editText=el.value.slice(0,3000);persist();}});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-reading]');if(!b||b.disabled)return;const a=b.dataset.reading,v=b.dataset.value,i=Number(b.dataset.index),s=active();
    if(a==='guide'){openGuide(v,b.dataset.scenario||'');return;}
    if(a==='guide-back'){if(data.ui.guideReturn==='table'){data.ui.view='table';persist();redraw(data.ui.resultY);}else{data.ui.view='gallery';persist();redraw(data.ui.galleryY);}return;}
    if(a==='category'){if(!groups.some(g=>g[0]===v)||data.ui.category===v)return;data.ui.category=v;persist();redraw(window.scrollY);return;}
    if(a==='start'){saveInputs();prepare();return;}
    if(a==='daily'){data.ui.galleryY=window.scrollY;openDaily();return;}
    if(a==='resume'){data.ui.view='table';data.ui.historyId='';data.ui.dailyHistory='';persist();redraw();return;}
    if(a==='pause'||a==='gallery'||a==='finish'||a==='new'){leaveTable();return;}
    if(a==='delete-history'){confirmHistoryDeletion(v);return;}if(a==='cancel-delete-history'){document.querySelector('[data-reading-delete-dialog]')?.close();return;}if(a==='confirm-delete-history'){if(!data.history.some(x=>x.id===v))return;data.history=data.history.filter(x=>x.id!==v);if(data.draft?.id===v)data.draft=null;data.ui.historyId='';data.ui.historyOpen=true;const y=window.scrollY;document.querySelector('[data-reading-delete-dialog]')?.close();persist();redraw(y);toast('这组记录已删除，其他记录和学习进度都保留了。');return;}
    if(a==='history'||a==='daily-history'){const item=a==='history'?data.history.find(x=>x.id===v):data.daily.find(x=>x.dailyDate===v);if(!item)return;data.ui.galleryY=window.scrollY;data.ui.historyOpen=true;data.ui.historyId=a==='history'?v:'';data.ui.dailyHistory=a==='daily-history'?v:'';if(item.phase!=='read'){if(data.draft&&!archive())return;data.draft=structuredClone(item);data.ui.historyId='';data.ui.dailyHistory='';}data.ui.view='table';persist();redraw();return;}
    if(a==='motion-pause'){pauseMotion();return;}if(a==='motion-replay'){replayMotion();return;}if(a==='skip-animation'){advanceMotion();return;}if(a==='cut'){cut(i);return;}
    if(a==='fan-in'){zoomFan(1.2);return;}if(a==='fan-out'){zoomFan(1/1.2);return;}if(a==='pick'){pick(i,b);return;}if(a==='undo'){undo();return;}
    if(a==='reveal'||a==='reveal-all'||a==='reveal-ai'){revealAll(!s.dailyDate&&online());return;}
    if(a==='ai-request'){requestAI(s);return;}if(a==='ai-cancel'){window.TarotReadingAI?.cancel(s);return;}
    if(a==='card'){openDetail(i,b);return;}if(a==='detail-zoom'){document.querySelector('.reading-detail-portrait')?.classList.toggle('zoomed');return;}if(a==='close-reference'){closeDetail();return;}
    if(a==='result-guide'&&s){openGuide(s.spreadId,s.scenarioId,true);return;}
    if(a==='edit-question'&&s){window.TarotReadingAI?.cancel(s);data.ui.resultY=window.scrollY;data.ui.editText=s.questionText||'';data.ui.view='edit';persist();redraw();return;}
    if(a==='edit-back'){data.ui.view='table';persist();redraw(data.ui.resultY);return;}
    if(a==='save-question'&&s){window.TarotReadingAI?.cancel(s);const q=data.ui.editText.trim();if(q!==s.questionText){if(s.ai?.length){if((s.answerHistory||[]).length>=20){toast('已保留多次回答，请先导出记录后开始新的一次。');return;}s.answerHistory=[...(s.answerHistory||[]),{questionText:s.questionText,ai:structuredClone(s.ai)}];}s.questionText=q;s.userQuestion=q;s.ai=[];for(const copy of [data.draft,...data.history,...data.daily])if(copy?.id===s.id)Object.assign(copy,structuredClone(s));}data.ui.view='table';persist();redraw();if(online()&&!s.dailyDate)requestAnimationFrame(()=>requestAI(s));return;}
    if(a==='save-again'){persist();redraw(window.scrollY);}
  });
  document.addEventListener('tarot-language-change',()=>{if(data.ui.view==='table'&&active()?.phase==='read')window.TarotReadingAI?.refresh(active());});
  window.addEventListener('pagehide',()=>{cancelTimers();if(data.draft?.phase==='reveal'&&data.draft.revealed.length===data.draft.picked.length){clearTimeout(revealTimer);revealTimer=null;data.draft.phase='read';}persist();});
  return {isFocused:()=>data.ui.view!=='gallery',render,renderGuide,learningHub,dashboard,openDaily,validate,export:()=>data,restore:raw=>{cancelTimers();data=validate(raw);persist();},reset:()=>{cancelTimers();data=blank();persist();}};
};
