/* Current app integration plus legacy-record preservation. Isolated public fixtures only. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),url=process.env.DEMO_URL||require('node:url').pathToFileURL(path.join(root,'demo/tarot-demo.html')).href,KEY='tarot-pocket-demo-v1';
const model={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'content.js'),'utf8'),model);const legacy=model.window.TAROT_CONTENT;
assert.equal(legacy.cards.length,12);assert.equal(legacy.questions.length,24);for(const q of legacy.questions){assert.equal(q.options.length,4);assert(q.options.every(o=>o.text&&o.reason));assert(q.options.some(o=>o.id===q.correct));}
const state=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);
const fits=async p=>assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'viewport overflow');
async function step(p){return p.evaluate(k=>{const s=JSON.parse(localStorage.getItem(k)).journey.academy.session;const step=TarotAcademy.stepFor(s);return {s,kind:step?.kind,correct:step?.question?.correct};},KEY);}
async function complete(p){for(let i=0;i<45;i++){const x=await step(p);if(x.s.complete)return;if(x.kind==='question'&&await p.locator('[data-academy=answer]:enabled').count())await p.locator(`[data-academy=answer][data-value="${x.correct}"]`).click();await p.locator('[data-academy=next]').click();}throw Error('lesson did not finish');}
(async()=>{const b=await chromium.launch(require('./browser_options.cjs'));try{
const c=await b.newContext({viewport:{width:390,height:844},acceptDownloads:true,reducedMotion:'reduce'}),p=await c.newPage(),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(new URL(url).origin))external.push(r.url());});await p.goto(url);await fits(p);
assert.deepEqual(await p.locator('.navitem').allTextContents(),['首页','学牌','抽牌']);assert.equal(await p.locator('[data-home-choice]').count(),2);
await p.locator('[data-action=status]').first().click();await p.getByText('78 / 78',{exact:true}).waitFor();await p.locator('#overlay [data-action=close]').click();
await p.locator('[data-action=choose-cards]').click();assert.equal(await p.locator('.library-card').count(),78);await p.locator('.library-card img').evaluateAll(async xs=>{for(const x of xs)x.loading='eager';await Promise.all(xs.map(x=>x.decode()));});assert(await p.locator('.library-card img').evaluateAll(xs=>xs.every(x=>x.naturalWidth>100)));
await p.locator('.library-card[data-id=p04]').click();await p.locator('[data-action=face][data-value=reversed]').click();assert.equal(await p.locator('#overlay .reversed-img').count(),1);await p.locator('[data-action=save]').click();assert((await state(p)).saved.includes('p04'));
await p.locator('[data-action=zoom]').click();await p.locator('#overlay [data-action=close]').click();assert.equal(await p.locator('#overlay [data-action=save]').count(),1,'zoom returns to the same card reference');
await p.locator('[data-academy=start][data-id=p04]').click();assert.equal(await p.locator('[data-action=confidence],[data-learn=rate],textarea').count(),0,'no self-rating or writing task');
await p.locator('[data-academy=next]').click();let x=await step(p);assert.equal(x.kind,'question');await p.locator(`[data-academy=answer][data-value="${x.correct}"]`).click();const saved=(await state(p)).journey.academy.session;await p.reload();await p.locator('[data-academy=continue]').first().click();assert.deepEqual((await state(p)).journey.academy.session.answers,saved.answers,'reload keeps the actual answer without scoring it twice');assert(await p.locator('[data-academy=answer]:disabled').count()>0);await complete(p);assert((await state(p)).journey.academy.progress.p04.uprightAt>0);
await p.locator('[data-academy=home]').first().click();await p.locator('.topbar [data-page=me]').click();
// A genuine old-format shape remains valid, including confidence as historical data only.
const oldState=await state(p),oldQuestion=legacy.questions[0];oldState.history.push({id:'synthetic-legacy',qid:oldQuestion.id,cardId:oldQuestion.cardId,at:1000,correct:true,confidence:'sure',hint:false,selected:oldQuestion.correct});oldState.schedules[oldQuestion.id]=2000;
// Use the real import route. Direct localStorage writes would be overwritten
// by app.js pagehide persistence, so they do not simulate a user migration.
await p.locator('#import-file').setInputFiles({name:'legacy-fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({app:'tarot-pocket-demo',version:1,state:oldState}))});await p.locator('[data-action=confirm-import]').click();assert.equal((await state(p)).history.at(-1).id,'synthetic-legacy');
await p.reload();await p.locator('.topbar [data-page=me]').click();assert.equal((await state(p)).history.at(-1).id,'synthetic-legacy','imported historical answer survives automatic pagehide save');
const download=p.waitForEvent('download');await p.locator('[data-action=export]').click();const f=await(await download).path(),backup=JSON.parse(fs.readFileSync(f));assert(backup.state.journey.academy.progress.p04.uprightAt);assert.equal(backup.state.history.at(-1).confidence,'sure');assert(backup.learning&&backup.reading);
await p.locator('[data-action=reset]').click();await p.locator('[data-action=confirm-reset]').click();assert.deepEqual((await state(p)).journey.academy.progress,{});await p.locator('.topbar [data-page=me]').click();await p.locator('#import-file').setInputFiles({name:'synthetic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await p.locator('[data-action=confirm-import]').click();assert.equal((await state(p)).history.at(-1).id,'synthetic-legacy');assert((await state(p)).journey.academy.progress.p04.uprightAt);assert((await state(p)).saved.includes('p04'));
const before=await state(p);await p.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"app":"wrong"}')});await p.locator('.toast').filter({hasText:'无法导入'}).waitFor();assert.deepEqual(await state(p),before);
const older=structuredClone(backup);delete older.state.journey;delete older.learning;delete older.reading;await p.locator('#import-file').setInputFiles({name:'older.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(older))});await p.locator('[data-action=confirm-import]').click();assert.deepEqual((await state(p)).journey.academy.progress,before.journey.academy.progress,'older backups do not erase new course progress');
await p.locator('[data-action=status]').first().click();await p.locator('[data-action=sources]').click();assert.equal(await p.locator('#overlay a[href*="commons.wikimedia.org/wiki/File:"]').count(),78);await p.locator('#overlay [data-action=close]').click();
await c.setOffline(true);await p.locator('.bottomnav [data-page=courses]').click();await p.locator('.academy-card-library [data-action=nav][data-page=library]').click();await p.locator('.library-card[data-id=c14]').click();await p.locator('.detail-start [data-academy][data-id=c14]').click();await complete(p);assert((await state(p)).journey.academy.progress.c14.completedAt);await c.setOffline(false);
const cold=await b.newContext();await cold.setOffline(true);const cp=await cold.newPage();await cp.goto(require('node:url').pathToFileURL(path.join(root,'demo/tarot-demo.html')).href);await cp.locator('[data-home-choice]').first().waitFor();await cold.close();
await p.locator('[data-academy=home]').first().click();await p.locator('.bottomnav [data-page=home]').click();for(const w of [320,375,390,430,1280]){await p.setViewportSize({width:w,height:844});await fits(p);}assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS: current learning integration, all 78 images, answer/reload/complete, no self-rating, favorites/zoom, all-three-key backup/reset/import/old-record preservation, provenance, offline lesson and cold start, five viewports.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
