/* Current guided-course contract. Uses synthetic records, never private progress. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {chromium}=require('playwright');
const legacyJourney=require('./legacy_journey_fixture.cjs');
const root=path.resolve(__dirname,'..'),model={window:{}};
for(const n of ['reading-deck.js','curriculum-content.js','guided-major.js','guided-minor.js','guided-learning.js','journey.js'])vm.runInNewContext(fs.readFileSync(path.join(root,n),'utf8'),model);
const guided=model.window.TarotGuided,api=model.window.TarotJourney,deck=Object.fromEntries(model.window.TAROT_READING_DECK.cards.map(c=>[c.id,c])),lessons=Object.fromEntries(model.window.TAROT_CURRICULUM.cards.map(c=>[c.id,c])),authored=guided.cards();
assert.equal(Object.keys(authored).length,78,'every freely selectable card needs the new authored course');
assert.deepEqual(Object.keys(authored).sort(),Object.keys(deck).sort());
for(const c of Object.values(authored)){
 assert(c.observe.length>10&&c.recall.length>15,c.id);
 for(const q of [c.reason,c.reversal]){assert(q.prompt.length>10,c.id);assert.equal(q.options.length,3);assert.deepEqual(Array.from(q.options,x=>x.id),['yes','near','over']);assert.equal(new Set(q.options.map(x=>x.text)).size,3);for(const o of q.options){assert(o.text.length>10,c.id);assert(o.feedback.length>20,c.id);assert(!Object.values(deck).some(x=>x.name===o.text),'no card-name recognition choices');}}
 assert(c.reversal.context.length>20,c.id+' needs evidence to distinguish possible reversals');
}
assert.equal(new Set(Object.values(authored).map(c=>c.reason.prompt)).size,78,'card-specific reasoning, not one generic quiz template');
assert.equal(new Set(Object.values(authored).map(c=>c.reversal.context)).size,78);
let contexts=0;
for(const c of Object.values(deck))for(const topic of ['career','love','study'])for(const part of [0,1]){
 const step=guided.makeStep('application',c,lessons[c.id],deck,{topic,guided:{part}});
 assert.equal(step.role,part?'advice':'tension');assert.equal(step.prompt,c.questions[topic]);assert.equal(step.options,undefined,'open contextual readings must not manufacture an exclusive correct answer');assert(c.contexts[topic][step.role].length>10);contexts++;
}
const sample={version:1,cards:{m02:{introducedAt:1,lastAt:1,rounds:0,skills:{},reflections:{recall:'synthetic memory sentence'}}},paused:{},session:{cardId:'m02',mode:'new',steps:['intro','image','meaning','compare','application','reversal','recall'],index:4,seed:30,topic:'career',position:'advice',startedAt:1,answers:{image:{selected:'yes',grade:4,correct:true,hint:false},meaning:{selected:'yes',grade:4,correct:true,hint:false},compare:{selected:'self-3',grade:3,correct:true,hint:false}},playVersion:4,variant:0,inspected:true,guided:{key:'application',part:1,selected:'',attempts:[{selected:'self-2',correct:false,hint:false}],marks:[],note:'synthetic note',compareSeen:false}}};
const restored=api.validate(sample,Object.keys(deck));assert.equal(restored.session.guided.part,1);assert.equal(restored.session.guided.attempts[0].correct,false);assert.equal(restored.cards.m02.reflections.recall,'synthetic memory sentence');assert.deepEqual(api.validate(restored,Object.keys(deck)),restored,'validated new records are idempotent, with every field checked');
const missingPresentation=JSON.parse(JSON.stringify(sample));missingPresentation.session.index=1;delete missingPresentation.session.guided;assert.equal(api.validate(missingPresentation,Object.keys(deck)).session.guided.selected,'yes','committed answer recovers presentation without scoring again');
const missingEarlier=JSON.parse(JSON.stringify(sample));delete missingEarlier.session.answers.image;const repaired=api.validate(missingEarlier,Object.keys(deck));assert.equal(repaired.session.index,1);assert.equal(repaired.session.guided.key,'image','repaired index and guided state must agree');
if(process.env.GUIDED_MODEL_ONLY==='1'){console.log(JSON.stringify({status:'PASS',cards:78,contexts}));process.exit(0);}
const key='tarot-pocket-demo-v1',read=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),key),session=async p=>(await read(p)).journey.session;
const url=process.env.DEMO_URL||'file://'+path.join(root,'demo/tarot-demo.html');
async function english(p){const found=await p.evaluate(()=>{const a=[],w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);for(let n=w.nextNode();n;n=w.nextNode())if(!n.parentElement.closest('script,style,noscript,[data-i18n-ignore]')&&/[\u3400-\u9fff]/.test(n.textContent))a.push(n.textContent.trim());return [...new Set(a)];});assert.deepEqual(found,[]);}
async function solve(p){let remaining=20;while(!(await session(p)).complete&&remaining--){const s=await session(p),k=s.steps[s.index];if(await p.evaluate(()=>document.documentElement.lang==='en'))await english(p);
 if(k==='intro'){if(!s.inspected)await p.locator('[data-journey=inspect]').click();}
 else if(!s.answers[k]){
  if(k==='meaning'){if(!s.guided.compareSeen)await p.locator('[data-guided=meaning-reveal]').click();await p.locator('[data-guided=meaning-rate][data-value="4"]').click();}
  else if(k==='application'){if(!s.guided.compareSeen)await p.locator('[data-guided=application-reveal]').click();if(!s.guided.selected)await p.locator('[data-guided=application-rate][data-value="4"]').click();if(!(await session(p)).guided.part){await p.locator('[data-guided=change-position]').click();await p.locator('[data-guided=application-reveal]').click();await p.locator('[data-guided=application-rate][data-value="4"]').click();}}
  else if(k==='compare'){if(!s.guided.compareSeen)await p.locator('[data-guided=compare-reveal]').click();await p.locator('[data-guided=compare-rate][data-value="4"]').click();}
  else if(k==='recall'){if(!s.revealed)await p.locator('[data-journey=reveal]').click();for(const id of ['image','meaning','application'])if(!(await session(p)).guided.marks.includes(id))await p.locator(`[data-guided=mark][data-value=${id}]`).click();await p.locator('[data-guided=save-recall]').click();}
  else{if(!s.guided.selected)await p.locator('[data-guided=answer][data-value=yes]').click();if(k==='application'&&!(await session(p)).guided.part){await p.locator('[data-guided=change-position]').click();await p.locator('[data-guided=answer][data-value=yes]').click();}}
 }
 if(await p.evaluate(()=>document.documentElement.lang==='en'))await english(p);
 if(await p.locator('[data-journey=next]').count())await p.locator('[data-journey=next]').click();
 }assert((await session(p)).complete);
}
(async()=>{const b=await chromium.launch(require('./browser_options.cjs'));try{
 const ctx=await b.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,reducedMotion:'reduce',acceptDownloads:true}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);
 const untranslated=await p.evaluate(()=>{TAROT_I18N.setLocale('en');const gaps=new Set(),d=Object.fromEntries(TAROT_READING_DECK.cards.map(c=>[c.id,c])),lessons=Object.fromEntries(TAROT_CURRICULUM.cards.map(c=>[c.id,c]));for(const c of Object.values(d))for(const k of ['intro','image','meaning','compare','application','reversal','recall'])for(const shown of [false,true]){const s={steps:[k],index:0,topic:'study',guided:{...TarotGuided.blank(k),part:shown?1:0,compareSeen:shown,selected:shown?'near':''},answers:{},inspected:shown,revealed:shown,hint:shown};const node=document.createElement('div');node.innerHTML=TarotGuided.render(c,lessons[c.id],d,s,{esc:v=>String(v).replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x])),img:()=>'',icon:()=>'',ordered:a=>a,head:'',scaffold:()=>''});const walker=document.createTreeWalker(node,NodeFilter.SHOW_TEXT);for(let n=walker.nextNode();n;n=walker.nextNode())if(!n.parentElement.closest('[data-i18n-ignore]')){const t=TAROT_I18N.translate(n.textContent);if(/[\u3400-\u9fff]/.test(t))gaps.add(t.trim());}}TAROT_I18N.setLocale('zh-CN');return [...gaps];});assert.equal(untranslated.length,0,'untranslated course text: '+JSON.stringify(untranslated.slice(0,12)));
 assert.equal(await p.locator('[data-home-choice][data-journey=new]').count(),1,'random new learning is the primary action');assert.equal(await p.locator('[data-home-choice]').count(),2);
 await p.locator('[data-action=choose-cards]').click();await p.locator('.library-card[data-id=m02]').click();await p.locator('[data-journey=start][data-id=m02]').click();assert.equal((await session(p)).playVersion,4);
 assert.equal(await p.locator('[data-journey=next]').count(),0);assert(!(await p.locator('.guided-stage').innerText()).includes(deck.m02.core),'the first observation does not give the meaning away');await p.locator('.guided-face img').evaluate(i=>i.decode());await p.locator('[data-journey=inspect]').click();await p.locator('[data-journey=next]').click();
 assert.equal(await p.locator('.guided-reference').count(),0,'answer-revealing references are not available before the tracked hint');assert.equal(await p.locator('.picture-options').count(),0,'no obvious three-picture matching in a new lesson');assert.equal(await p.locator('[data-guided=answer]').count(),3);assert((await p.locator('.guided-question').innerText()).includes(authored.m02.reason.prompt));
 for(const width of [320,390,430,1280]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));for(const option of await p.locator('[data-guided=answer]').all()){const box=await option.boundingBox();assert(box.height>=44);}}await p.setViewportSize({width:390,height:844});
 await p.screenshot({path:'/tmp/tarot-v14-guided-reason.png',fullPage:true});
 await p.locator('[data-guided=answer][data-value=near]').click();assert.match(await p.locator('.journey-feedback>strong').innerText(),/答错了/);assert((await p.locator('.journey-feedback').innerText()).includes(authored.m02.reason.options[1].feedback));
 const before=await read(p);await p.reload();await p.locator('[data-journey=continue]').click();const after=await read(p);assert.deepEqual(after.journey,before.journey,'whole current journey survives reload exactly');await p.locator('[data-journey=next]').click();
 assert.equal(await p.locator('.guided-framework').count(),1);assert.equal(await p.locator('[data-guided=answer]').count(),0);await p.locator('[data-guided=meaning-reveal]').click();await p.locator('[data-guided=meaning-rate][data-value="4"]').click();await p.locator('[data-journey=next]').click();assert.equal(await p.locator('.guided-pair img').count(),2);await p.locator('[data-guided=compare-reveal]').click();await p.locator('[data-guided=compare-rate][data-value="3"]').click();await p.locator('[data-journey=next]').click();
 const prompt=await p.locator('.guided-case>p').first().innerText();assert.equal(await p.locator('[data-guided=answer]').count(),0,'several valid advice readings cannot be marked wrong');await p.locator('[data-guided=application-reveal]').click();await p.locator('[data-guided=application-rate][data-value="2"]').click();assert.equal((await read(p)).journey.cards.m02.skills.application,undefined,'first half alone does not grade the whole position change');await p.locator('[data-guided=change-position]').click();assert.equal(await p.locator('.guided-case>p').first().innerText(),prompt,'only the position changes');assert.equal(await p.locator('.guided-slot.occupied strong').innerText(),'建议');
 const half=await read(p);await p.reload();await p.locator('[data-journey=continue]').click();assert.deepEqual((await read(p)).journey,half.journey);await p.locator('[data-guided=application-reveal]').click();await p.locator('[data-guided=application-rate][data-value="4"]').click();assert.equal((await read(p)).journey.cards.m02.skills.application.grade,2,'second self-assessment cannot erase first difficulty');await p.locator('[data-journey=next]').click();
 assert.equal(await p.locator('.guided-context').innerText(),authored.m02.reversal.context);await p.locator('[data-guided=answer][data-value=yes]').click();await p.locator('[data-journey=next]').click();assert.equal(await p.locator('.guided-stage img').count(),0,'independent reconstruction really hides all card images');assert(!(await p.locator('.guided-stage').innerText()).includes(authored.m02.recall),'the card-specific cue is hidden before independent recall');assert.equal(await p.locator('[data-guided=answer]').count(),0);await p.locator('.guided-own-note>summary').click();await p.locator('[data-guided-note]').fill('synthetic personal recall, not automatically graded');await p.locator('[data-journey=reveal]').click();for(const id of ['image','meaning','application'])await p.locator(`[data-guided=mark][data-value=${id}]`).click();await p.locator('[data-guided=save-recall]').click();await p.locator('[data-journey=next]').click();
 const done=await read(p);assert.equal(done.journey.cards.m02.rounds,1);assert.equal(Object.keys(done.journey.cards.m02.skills).length,6);assert.equal(done.journey.cards.m02.reflections.recall,'synthetic personal recall, not automatically graded');
 await p.locator('[data-journey=next-card]').click();const random=new Set(['m02']);for(let i=0;i<8;i++){const s=await session(p);assert(!random.has(s.cardId),'random exploration avoids already started cards');random.add(s.cardId);await p.locator('[data-action=nav][data-page=home]').first().click();assert.equal(await p.locator('[data-journey=continue]').count(),1,'resume remains separate from primary random button');await p.locator('[data-home-choice][data-journey=new]').click();}
 await p.locator('[data-language-toggle]').click();await english(p);await solve(p);await english(p);
 await p.locator('[data-action=nav][data-page=home]').last().click();await p.locator('[data-action=choose-cards]').click();await p.locator('.library-card[data-id=p04]').click();await p.locator('[data-journey=start][data-id=p04]').click();await solve(p);await english(p);
 // Explicit upgrade preserves the learning record; old flows still have a way out.
 await p.locator('[data-journey=next-card]').click();await legacyJourney(p,3);const oldCards=(await read(p)).journey.cards;await p.locator('[data-journey=upgrade]').click();assert.equal((await session(p)).playVersion,4);assert.deepEqual((await read(p)).journey.cards,oldCards);await english(p);

 const recallCtx=await b.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),rp=await recallCtx.newPage();await rp.goto(url);await rp.locator('[data-action=choose-cards]').click();await rp.locator('.library-card[data-id=m02]').click();await rp.locator('[data-journey=start][data-id=m02]').click();await solve(rp);await rp.locator('[data-journey=repeat]').click();assert.equal((await session(rp)).steps[0],'recall');await rp.locator('[data-guided=recall-hint]').click();assert((await rp.locator('.guided-stage').innerText()).includes(authored.m02.recall));await rp.locator('[data-journey=reveal]').click();for(const id of ['image','meaning','application'])await rp.locator(`[data-guided=mark][data-value=${id}]`).click();await rp.locator('[data-guided=save-recall]').click();assert.equal((await session(rp)).answers.recall.grade,2);assert.equal((await session(rp)).answers.recall.hint,true);await recallCtx.close();
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',cards:78,authoredQuestions:156,positionContexts:contexts,checks:['random primary and separate resume','card-specific causal feedback','compact mobile questions','six skill scores and honest self-report','same-question two-position reasoning','exact new-session reload','first-attempt grading retained','hidden-image reconstruction','local own-word note','bilingual course','explicit legacy-course upgrade'],physicalIPhone:false}));await ctx.close();
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
