/* A persisted cut changes order exactly once; animation never supplies randomness. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const root=path.resolve(__dirname,'..'),memory=new Map(),handlers={},timers=new Map();let time=new Date(2026,8,14,12).getTime(),counter=0;
const model={window:{addEventListener(){},scrollTo(){}},document:{addEventListener(type,fn){handlers[type]=fn;},querySelector(){return null;}},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},matchMedia:()=>({matches:true}),crypto:webcrypto,Uint32Array,structuredClone,Date,clearTimeout:id=>timers.delete(id),setTimeout:fn=>{timers.set(++counter,fn);return counter;},requestAnimationFrame:fn=>fn()};
for(const f of ['reading-deck.js','spread-content.js','reading.js'])vm.runInNewContext(fs.readFileSync(path.join(root,f),'utf8'),model);
let api;const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));api=model.window.createTarotReading({esc,img:id=>`<img src="${id}">`,icon:()=>'',go:()=>api.render(),toast(){},now:()=>time});
const snapshot=()=>JSON.parse(JSON.stringify(api.export()));const click=(action,value,index)=>handlers.click({target:{closest:()=>({dataset:{reading:action,value,index}})}});const finish=()=>click('skip-animation');
assert.equal(model.window.TAROT_SPREAD_CONTENT.spreads.length,27);
click('use-spread','work-progress');click('start');let before=snapshot();assert.equal(before.draft.phase,'shuffling');assert.equal(before.settings.topic,'career');assert.equal(before.settings.contextEnabled,true);assert.equal(new Set(before.draft.pool.map(c=>c.id)).size,78);
click('pause');assert.equal(snapshot().ui.view,'gallery');assert.equal(snapshot().draft.phase,'shuffling');api.restore(snapshot());click('resume');finish();assert.equal(snapshot().draft.phase,'cut');assert.deepEqual(snapshot().draft.pool,before.draft.pool);
click('cut',undefined,26);const cut=snapshot();assert.equal(cut.draft.phase,'cutting');assert.equal(cut.draft.cutOffset,26);assert.deepEqual(cut.draft.pool,[...before.draft.pool.slice(26),...before.draft.pool.slice(0,26)]);click('cut',undefined,52);assert.deepEqual(snapshot().draft.pool,cut.draft.pool);api.restore(snapshot());finish();assert.equal(snapshot().draft.phase,'pick');assert.deepEqual(snapshot().draft.pool,cut.draft.pool);assert(!api.render().includes('<img '),'unrevealed selection has no image identities');
click('pick',undefined,0);click('pick',undefined,0);assert.deepEqual(snapshot().draft.picked,[0]);click('card',undefined,0);assert.deepEqual(snapshot().draft.revealed,[0]);click('pause');api.restore(snapshot());assert.equal(snapshot().ui.view,'gallery');click('resume');assert.deepEqual(snapshot().draft.pool,cut.draft.pool);assert.deepEqual(snapshot().draft.picked,[0]);
click('new');assert.equal(snapshot().history.length,1);click('daily');assert.equal(snapshot().draft.dailyDate,'2026-09-14');finish();click('cut',undefined,39);finish();click('pick',undefined,5);click('card',undefined,0);const daily=snapshot();assert.equal(daily.daily.length,1);assert.equal(daily.draft.phase,'read');click('finish');click('daily');assert.equal(snapshot().draft.id,daily.draft.id);assert.deepEqual(snapshot().draft.pool,daily.draft.pool);assert.deepEqual(snapshot().draft.picked,[5]);
click('finish');time+=86400000;click('daily');assert.equal(snapshot().draft.dailyDate,'2026-09-15');assert.notEqual(snapshot().draft.id,daily.draft.id);assert.equal(snapshot().daily.length,2);const legacy=snapshot();delete legacy.daily;api.restore(legacy);assert.equal(snapshot().daily.length,2,'legacy backups must not erase new daily records');const invalid=snapshot();invalid.daily.push(invalid.daily[0]);assert.throws(()=>api.validate(invalid));
const current=snapshot();current.draft.phase='cut';api.restore(current);click('gallery');const html=api.render();assert(html.includes('reading-categories'));assert(!html.includes('context-picker'));assert(html.includes('data-reading="daily"'));click('category','love');assert(!api.render().includes('data-value="work-team"'));click('guide','love-talk');assert.equal(snapshot().ui.view,'detail');assert(api.renderGuide().includes('倾听盲点'));click('guide-back');assert.equal(snapshot().ui.view,'gallery');click('use-spread','love-talk');assert.equal(snapshot().settings.topic,'love');assert.equal(snapshot().settings.contextEnabled,true);assert(!api.render().includes('data-reading="topic"'));click('question-back');assert.equal(snapshot().ui.view,'detail');
console.log(JSON.stringify({status:'PASS',checks:['8 active definitions and 19 legacy definitions','durable shuffle/cut/pick/exit phases','cut rotates existing deck exactly once','no card-face DOM leakage','duplicate picks rejected','daily stable local date and rollover','daily preserved on legacy import','scenario categories set reading context','guide/setup navigation always exits']}));
