/* Current learning-library interaction contract, including the historic focus/scroll regressions. */
const assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright');
const url=process.env.DEMO_URL||require('node:url').pathToFileURL(path.resolve(__dirname,'../demo/tarot-demo.html')).href;
(async()=>{const b=await chromium.launch(require('./browser_options.cjs'));try{const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);
await p.locator('[data-action=choose-cards]').click();await p.locator('[data-action=filter][data-value=收藏]').click();assert.equal(await p.evaluate(()=>document.activeElement.dataset.value),'收藏');await p.locator('[data-action=filter][data-value=全部]').click();assert.equal(await p.locator('.library-card').count(),78);
await p.locator('[data-library-search]').fill('圣杯');const search=await p.locator('[data-library-search]').elementHandle();await p.locator('[data-library-search]').fill('圣杯七');assert.equal(await p.locator('.library-card').count(),1);assert(await search.evaluate(e=>e===document.activeElement));await p.locator('[data-library-search]').fill('');await p.locator('.library-card[data-id=p04]').scrollIntoViewIfNeeded();const y=await p.evaluate(()=>scrollY);await p.locator('.library-card[data-id=p04]').click();const sheet=await p.locator('.sheet').elementHandle();
for(const selector of ['[data-action=face][data-value=reversed]','[data-action=save]']){await p.locator(selector).scrollIntoViewIfNeeded();const sy=await sheet.evaluate(e=>e.scrollTop);await p.locator(selector).click();assert(await sheet.evaluate(e=>e===document.querySelector('.sheet')));assert(Math.abs(await sheet.evaluate(e=>e.scrollTop)-sy)<2);}
assert.equal(await p.locator('[data-action=learn-card],.dossier-pair').count(),0,'No arbitrary read marker or unfamiliar-card comparison');await p.locator('[data-action=zoom]').scrollIntoViewIfNeeded();const sy=await sheet.evaluate(e=>e.scrollTop);await p.locator('[data-action=zoom]').click();await p.keyboard.press('Escape');assert(await sheet.evaluate(e=>e===document.querySelector('.sheet')));assert.equal(await sheet.evaluate(e=>e.scrollTop),sy);await p.locator('#overlay [data-action=close]').click();assert(Math.abs(await p.evaluate(()=>scrollY)-y)<2);
await p.locator('.bottomnav [data-page=courses]').click();for(const [level,count] of [['B',8],['I',6],['A',6]]){await p.locator(`[data-academy=level][data-value=${level}]`).click();assert.equal(await p.locator('.academy-lesson').count(),count);assert.equal(await p.locator(`[data-academy=level][data-value=${level}]`).getAttribute('aria-pressed'),'true');}
await p.locator('[data-academy=start][data-id=A05]').click();assert.equal(await p.locator('[data-reading]').count(),0,'Authored lesson is separate from personal reading');assert.equal(await p.locator('.academy-image-space figure').count(),5);assert.equal(await p.locator('[data-academy=path]').count(),0,'A static worked spread does not add path controls');assert.equal(await p.locator('.academy-image-space figure.is-emphasized').count(),5);await p.locator('[data-language-toggle]').click();assert(!/[\u3400-\u9fff]/.test(await p.locator('.academy-shell').innerText()));for(const width of [320,390,430,1280]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert.deepEqual(errors,[]);console.log('PASS: 78 self-selected cards, live search focus, filters, same-sheet favorite/direction/zoom/scroll return, 8/6/6 course stages, static worked comparison spread separate from readings, bilingual 320–1280 layout.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
