/* Real mobile taps, held motion, all 78 choices, and durable staged reveals. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..'),KEY='tarot-reading-v3';
const state=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);
const click=(p,a,i)=>p.locator(`[data-reading="${a}"]${i===undefined?'':`[data-index="${i}"]`}`).first().click();
(async()=>{
 let server,url=process.env.DEMO_URL;
 if(!url){server=http.createServer((req,res)=>{
  const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html';
  if(rel==='locales/en.js'){const dict=Object.assign({},...fs.readdirSync(path.join(root,'locales')).filter(n=>/^en-.*\.json$/.test(n)).sort().map(n=>JSON.parse(fs.readFileSync(path.join(root,'locales',n),'utf8'))));res.setHeader('Content-Type','text/javascript');res.end('window.TAROT_EN='+JSON.stringify(dict));return;}
  if(!/\.(html|js|css|json|webp|png|svg|webmanifest)$/.test(rel)||/^(server|node_modules|\.)/.test(rel)){res.statusCode=403;res.end();return;}
  const file=path.join(root,rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.statusCode=404;res.end();return;}
  res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${server.address().port}/index.html`;}
 const browser=await chromium.launch(require('./browser_options.cjs'));
 try{
  const errors=[],ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await ctx.addInitScript(()=>sessionStorage.setItem('tarot-pocket-session-v1',JSON.stringify({token:'tp1.'+'r'.repeat(80),expiresAt:Date.now()+3600000})));await p.goto(url);await p.locator('.bottomnav [data-page=reading]').click();await p.locator('[data-reading=guide][data-value=three]').click();await p.locator('[data-reading=use-spread]').click();await click(p,'start');
  const original=await state(p),raw=structuredClone(original);
  const button=p.locator('[data-reading=motion-continue]');assert(await button.isDisabled(),'normal motion leaves time to watch');await p.waitForTimeout(220);const a=await p.locator('.ritual-pack>.reading-back').first().evaluate(e=>getComputedStyle(e).transform);await p.waitForTimeout(350);const b=await p.locator('.ritual-pack>.reading-back').first().evaluate(e=>getComputedStyle(e).transform);assert.notEqual(a,b);
  await p.waitForFunction(()=>!document.querySelector('[data-reading="motion-continue"]').disabled);await p.waitForTimeout(160);assert.equal((await state(p)).draft.phase,'shuffling','finished animation never takes control away from the user');await p.screenshot({path:'/tmp/tarot-v13-shuffle.png',fullPage:false});await click(p,'motion-continue');
  await click(p,'cut',52);assert(await p.locator('[data-reading=motion-continue]').isDisabled());const cut=await state(p);assert.deepEqual(cut.draft.pool,[...original.draft.pool.slice(52),...original.draft.pool.slice(0,52)]);await p.waitForFunction(()=>!document.querySelector('[data-reading="motion-continue"]').disabled);assert.equal((await state(p)).draft.phase,'cutting');await click(p,'motion-continue');
  const indices=await p.locator('[data-reading=pick]').evaluateAll(es=>es.map(e=>Number(e.dataset.index)));
  assert.deepEqual(indices,Array.from({length:78},(_,i)=>i),'all cards are present without paging');assert.equal(await p.locator('.whole-deck-grid img').count(),0);
  const boxes=await p.locator('[data-reading=pick]').evaluateAll(es=>es.map(e=>{const b=e.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height};}));
  assert(boxes.every(b=>b.w>=44&&b.h>=44));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert(a.x+a.w<=b.x+.5||b.x+b.w<=a.x+.5||a.y+a.h<=b.y+.5||b.y+b.h<=a.y+.5,'touch rectangles must not overlap');}
  await click(p,'pick',77);assert.deepEqual((await state(p)).draft.picked,[77]);assert.equal((await state(p)).draft.pendingPick,null);assert.equal(await p.locator('.was-picked').count(),1);await p.screenshot({path:'/tmp/tarot-v16-select.png',fullPage:true});
  await p.reload();await p.locator('.bottomnav [data-page=reading]').click();assert.deepEqual((await state(p)).draft.picked,[77]);assert.deepEqual((await state(p)).draft.pool,cut.draft.pool);
  await p.locator('[data-reading=pick][data-index="77"]').evaluate(e=>{e.click();e.click();});assert.deepEqual((await state(p)).draft.picked,[77]);
  await p.locator('.reading-sticky-head').evaluate(e=>e.dataset.identity='kept');await click(p,'pick',0);assert.equal(await p.locator('.reading-sticky-head').getAttribute('data-identity'),'kept');await click(p,'pick',1);assert.equal((await state(p)).draft.phase,'reveal');
  assert.equal(await p.locator('.reveal-group img').count(),0);await click(p,'reveal-all');assert.deepEqual((await state(p)).draft.revealed,[0,1,2]);assert.equal(await p.locator('.reveal-group img').count(),3);assert.equal(await p.locator('.reading-interpretation').count(),0);
  assert(await p.locator('[data-reading=reveal-all]').isDisabled(),'normal group flip leaves time to watch');assert.equal(await p.locator('.group-flip-back').count(),3);
  await p.waitForTimeout(160);await p.screenshot({path:'/tmp/tarot-v16-reveal.png',fullPage:false});
  // Leaving during a group flip must not strand the resumed table on a disabled button.
  await click(p,'pause');await click(p,'resume');assert.equal((await state(p)).draft.phase,'read');assert.equal(await p.locator('[data-reading-ai]').count(),1);assert.equal(await p.locator('.group-flip-back').count(),0);
  // Both persisted in-flight group state and the old final per-card acknowledgement recover safely.
  const interrupted=await state(p);
  for(const revealPending of [null,2]){
   const fixture=structuredClone(interrupted);fixture.draft.phase='reveal';fixture.draft.revealPending=revealPending;fixture.draft.revealed=[0,1,2];
   const recovery=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
   await recovery.addInitScript(({KEY,fixture})=>{localStorage.setItem(KEY,JSON.stringify(fixture));sessionStorage.setItem('tarot-pocket-session-v1',JSON.stringify({token:'tp1.'+'r'.repeat(80),expiresAt:Date.now()+3600000}));},{KEY,fixture});
   const restored=await recovery.newPage();restored.on('pageerror',e=>errors.push(e.message));await restored.goto(url);await restored.locator('.bottomnav [data-page=reading]').click();
   const saved=await state(restored);assert.equal(saved.draft.phase,'read');assert.deepEqual(saved.draft.revealed,[0,1,2]);assert.equal(saved.draft.revealPending,null);assert.deepEqual(saved.draft.pool,fixture.draft.pool);assert.deepEqual(saved.draft.picked,fixture.draft.picked);assert.equal(await restored.locator('.group-flip-back').count(),0);assert.equal(await restored.locator('[data-reading-ai]').count(),1);await recovery.close();
  }
  await p.reload();await p.locator('.bottomnav [data-page=reading]').click();assert.equal((await state(p)).draft.phase,'read');assert.deepEqual((await state(p)).draft.revealed,[0,1,2]);assert.equal(await p.locator('.group-flip-back').count(),0);
  const normal=await state(p);assert.equal(normal.draft.phase,'read');assert.equal(await p.locator('.reading-slot.active').count(),0);assert.equal(await p.locator('.reading-interpretation').count(),0);assert.equal(await p.locator('[data-reading-ai]').count(),1,'whole-spread result is the primary report');const connected=await p.evaluate(()=>!window.TAROT_STANDALONE&&!!window.TAROT_AI_CONFIG?.endpoint);assert.equal(await p.locator('[data-reading=ai-request]').count(),connected?1:0,'only a connected web edition exposes an AI request');if(await p.evaluate(()=>!!window.TAROT_STANDALONE))assert.match(await p.locator('[data-reading-ai]').innerText(),/独立离线文件/);await click(p,'card',0);await click(p,'card',0);assert.equal(await p.locator('.reading-interpretation').count(),0);
  // Replay the exact same already-randomized pool with reduced motion and the skip actions.
  const fast=await browser.newContext({viewport:{width:320,height:740},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),q=await fast.newPage();q.on('pageerror',e=>errors.push(e.message));await q.addInitScript(({KEY,raw})=>{localStorage.setItem(KEY,JSON.stringify(raw));sessionStorage.setItem('tarot-pocket-session-v1',JSON.stringify({token:'tp1.'+'r'.repeat(80),expiresAt:Date.now()+3600000}));},{KEY,raw});await q.goto(url);await q.locator('.bottomnav [data-page=reading]').click();await q.locator('[data-language-toggle]').click();
  const English=async()=>{await q.waitForTimeout(30);const text=await q.locator('body').evaluate(el=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n,out=[];while(n=walker.nextNode())if(/[\u3400-\u9fff]/.test(n.nodeValue)&&n.parentElement.checkVisibility()&&!n.parentElement.closest('[data-i18n-ignore],script,style'))out.push(n.nodeValue);return out;});assert.deepEqual(text,[]);assert(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));};
  await English();await click(q,'skip-animation');await English();await click(q,'cut',52);await English();await click(q,'skip-animation');await English();
  for(const i of [77,0,1])await click(q,'pick',i);await English();await click(q,'reveal-all');await English();
  const reduced=await state(q);assert.deepEqual(reduced.draft.pool,normal.draft.pool);assert.deepEqual(reduced.draft.picked,normal.draft.picked);assert.deepEqual(reduced.draft.revealed,normal.draft.revealed);assert.equal(reduced.draft.phase,'read');assert.deepEqual(errors,[]);
  await ctx.close();await fast.close();console.log(JSON.stringify({status:'PASS',checks:['normal shuffle and cut wait for explicit continuation','all 78 cards in one non-overlapping overview','one tap commits exactly once','choices survive reload','selection preserves surrounding DOM','one group reveal with held animation','pause/resume during group flip recovers all faces','persisted group flip restores all faces','legacy final acknowledgement restores completed result','whole-spread result with optional deselectable cards','normal and reduced/skip paths preserve identical deck and outcome','English ritual screens at 320px have no overflow or untranslated text']}));
 }finally{await browser.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}}
})().catch(e=>{console.error(e);process.exitCode=1;});
