const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const {chromium} = require('playwright');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const model = {window:{}};
vm.runInNewContext(fs.readFileSync(path.join(root,'content.js'),'utf8'),model);
const data = model.window.TAROT_CONTENT;
assert.equal(data.cards.length,12);
assert.equal(data.questions.length,24);
assert.equal(new Set(data.cards.map(c=>c.id)).size,12);
assert.equal(new Set(data.questions.map(q=>q.id)).size,24);
for(const q of data.questions){
  assert(data.cards.some(c=>c.id===q.cardId));
  assert.equal(q.options.length,4);
  assert.equal(new Set(q.options.map(o=>o.id)).size,4);
  assert(q.options.some(o=>o.id===q.correct));
  assert(q.options.every(o=>o.reason && o.text));
}
const url=process.env.DEMO_URL || 'http://127.0.0.1:8765/tarot-demo.html';
const key='tarot-pocket-demo-v1';
const state=page=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
const widthCheck=async page=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page overflows viewport');
(async()=>{
 const browser=await chromium.launch(require('./browser_options.cjs'));
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,acceptDownloads:true});
 const page=await context.newPage();
 page.setDefaultTimeout(90000);page.setDefaultNavigationTimeout(120000);
 const errors=[];const external=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(new URL(url).origin))external.push(r.url());});
 await page.goto(url);
 await page.evaluate(async()=>Promise.all([...document.images].map(x=>x.decode())));
 await widthCheck(page);
 await page.screenshot({path:'/tmp/tarot-demo-home-mobile.png',fullPage:true});
 await page.locator('[data-action=status]').first().click();
 await page.getByText('78 / 78',{exact:true}).waitFor();
 await page.locator('#overlay [data-action=close]').click();
 await page.locator('[data-action=start][data-mode=daily]').click();
 await page.locator('button.primary[data-action=draw]').click();
 if(await page.locator('[data-action=intro-next]').count())await page.locator('[data-action=intro-next]').click();
 await page.screenshot({path:'/tmp/tarot-demo-quiz-mobile.png',fullPage:true});
 let s=await state(page);const q=data.questions.find(q=>q.id===s.session.ids[0]);
 await page.locator(`[data-action=answer][data-value="${q.correct}"]`).click();
 assert.match(await page.locator('.feedbacktitle').innerText(),/答对了/);
 assert.equal((await state(page)).history.length,1);
 await page.locator('[data-action=confidence][data-value=sure]').click();
 s=await state(page);assert.equal(s.history[0].confidence,'sure');
 assert.equal(s.schedules[q.id]-s.history[0].at,3*86400000);
 const order=JSON.stringify(s.session.order);
 await page.reload();
 await page.locator('[data-action=resume]').click();
 assert.equal(JSON.stringify((await state(page)).session.order),order);
 assert.equal(await page.locator('[data-action=answer]:disabled').count(),4);
 assert.equal((await state(page)).history.length,1);
 await page.screenshot({path:'/tmp/tarot-demo-feedback-mobile.png',fullPage:true});
 for(let i=1;i<6;i++){
   await page.locator('[data-action=next]').click();
   if(i===1){await page.locator('[data-action=hint]').click();assert(await page.locator('.hint').count());}
   await page.locator('[data-action=unknown]').click();
 }
 await page.locator('[data-action=next]').click();
 await page.getByRole('heading',{name:'又多懂了一点。'}).waitFor();
 assert.equal((await state(page)).history.length,6);
 await page.locator('.complete [data-action=nav]').click();
 await page.locator('.bottomnav [data-page=library]').click();
 assert.equal(await page.locator('.library-card').count(),78);
 // Load off-screen lazy images before checking the entire 78-card asset set.
 await page.locator('.library-card img').evaluateAll(async images=>{
   for(const image of images)image.loading='eager';
   await Promise.all(images.map(image=>image.decode()));
 });
 assert(await page.locator('.library-card img').evaluateAll(xs=>xs.every(x=>x.naturalWidth>100)));
 await page.locator('[data-action=card][data-id=p04]').click();
 await page.locator('[data-action=face][data-value=reversed]').click();
 assert.equal(await page.locator('#overlay .reversed-img').count(),1);
 await page.locator('[data-action=detail-position][data-value=advice]').click();
 await page.locator('[data-action=save]').click();
 assert((await state(page)).saved.includes('p04'));
 await page.locator('#overlay [data-action=zoom]').click();
 await page.locator('#overlay [data-action=close]').click();
 assert.equal(await page.locator('#overlay [data-action=save]').count(),1,'zoom should return to details');
 await page.locator('#overlay [data-action=close]').click();
 await page.locator('[data-action=filter][data-value=收藏]').click();
 assert.equal(await page.locator('.library-card').count(),1);
 for(const id of ['one','three','choice']){
   await page.locator('.bottomnav [data-page=home]').click();
   await page.getByText('原有三个教学案例',{exact:true}).click();
   await page.locator(`[data-action=spread][data-id=${id}]`).click();
   assert.equal(await page.locator('.spread-slot').count(),id==='one'?1:id==='three'?3:6);
   await page.locator('[data-action=spread-answer][data-index="1"]').click();
   assert.equal(await page.locator('[data-action=spread-answer].correct').count(),1);
   await widthCheck(page);
   if(id==='three')await page.screenshot({path:'/tmp/tarot-demo-spread-mobile.png',fullPage:true});
   await page.locator('[data-reading=use-spread]').click();
   await page.locator('[data-reading=start]').click();
   await page.locator('[data-reading=pick]').first().waitFor();
   const n=id==='one'?1:id==='three'?3:6;
   for(let i=0;i<n;i++)await page.locator(`[data-reading=pick][data-index="${i}"]`).click();
   for(let i=0;i<n;i++)await page.locator(`[data-reading=card][data-index="${i}"]`).click();
   const imgs=await page.locator('.reading-slot.revealed img').evaluateAll(xs=>xs.map(x=>x.src));
   assert.equal(imgs.length,n);assert.equal(new Set(imgs).size,n);
   assert.equal(await page.locator('[data-action=spread-answer]').count(),0);
   await page.locator('[data-reading=finish]').click();
 }
 await page.locator('.bottomnav [data-page=me]').click();
 await page.locator('[data-action=advance]').click();assert.equal((await state(page)).offsetDays,3);
 const download=page.waitForEvent('download');await page.locator('[data-action=export]').click();
 const saved=await download;const file=await saved.path();const exported=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(exported.state.history.length,6);
 await page.locator('[data-action=reset]').click();await page.locator('[data-action=confirm-reset]').click();assert.equal((await state(page)).history.length,0);
 await page.locator('.bottomnav [data-page=me]').click();
 await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
 await page.locator('[data-action=confirm-import]').click();assert.equal((await state(page)).history.length,6);assert.equal((await state(page)).session,null);
 await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"app":"wrong"}')});
 await page.locator('.toast').filter({hasText:'无法导入'}).waitFor();assert.equal((await state(page)).history.length,6);
 await page.locator('[data-action=feedback]').click();await page.locator('[data-action=feedback-save]').first().click();assert.equal((await state(page)).feedback.length,1);
 await page.locator('[data-action=status]').first().click();await page.getByText('78 / 78',{exact:true}).waitFor();await page.locator('[data-action=sources]').click();assert.equal(await page.locator('#overlay a[href*="commons.wikimedia.org/wiki/File:"]').count(),78);await page.locator('#overlay [data-action=close]').click();
 await context.setOffline(true);
 await page.locator('.bottomnav [data-page=library]').click();await page.locator('[data-action=filter][data-value=全部]').click();
 await page.locator('[data-action=card][data-id=c14]').click();await page.locator('[data-action=card-practice]').click();await page.locator('button.primary[data-action=draw]').click();
 if(await page.locator('[data-action=intro-next]').count())await page.locator('[data-action=intro-next]').click();await page.locator('[data-action=unknown]').click();
 assert(await page.locator('.answer-feedback').count());
 await context.setOffline(false);
 const local=await browser.newContext({viewport:{width:390,height:844}});await local.setOffline(true);const lp=await local.newPage();await lp.goto('file://'+path.join(root,'demo/tarot-demo.html'));await lp.locator('[data-action=start][data-mode=daily]').waitFor();await lp.locator('[data-action=status]').first().click();await lp.getByText('78 / 78',{exact:true}).waitFor();await local.close();
 const desktop=await context.newPage();await desktop.setViewportSize({width:1280,height:900});await desktop.goto(url);await widthCheck(desktop);await desktop.screenshot({path:'/tmp/tarot-demo-home-desktop.png',fullPage:true});
 for(const w of [320,375,430]){await desktop.setViewportSize({width:w,height:844});await widthCheck(desktop);}
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 console.log(JSON.stringify({status:'PASS',cards:78,teachingSampleCards:12,questions:24,checks:['mobile layout','78 images decode','6-question session','answer scoring','confidence scheduling','reload resume and no duplicate answer','card detail/reversal/favorite','zoom return','3 legacy spreads and complete-deck free draws','demo date','export/import/reset','invalid import preserves records','feedback local-only','embedded asset provenance','offline navigation','offline file cold start in desktop Chromium','320/375/390/430/1280 widths','no runtime errors','no external runtime requests'],screenshots:'/tmp/tarot-demo-*.png',limitations:['real iPhone Safari not tested','PWA not implemented','demo scheduling only']},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
