/* Local synthetic responsive audit; no AI/provider requests or personal browser state. */
'use strict';
const assert=require('node:assert/strict'),{chromium,webkit}=require('playwright'),h=require('./reading_ui_harness.cjs');
const sizes=[[320,568],[390,844],[600,800],[768,1024],[1024,768],[1720,1000],[844,390]].filter(([width])=>!process.env.AUDIT_WIDTH||width===Number(process.env.AUDIT_WIDTH));
async function fits(p,label){const g=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(g.scroll<=g.width+1,label+' horizontal overflow '+JSON.stringify(g));}
async function reachable(p,selector,label){const el=p.locator(selector).first();await el.scrollIntoViewIfNeeded();const g=await el.evaluate(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {x:r.x,y:r.y,w:r.width,h:r.height,hit:e.contains(hit),vw:innerWidth,vh:innerHeight};});assert(g.x>=-1&&g.x+g.w<=g.vw+1&&g.y>=-1&&g.y+g.h<=g.vh+1&&g.hit,label+' inaccessible '+JSON.stringify(g));}
async function audit(name,engine){const server=await h.server(),browser=await engine.launch(name==='chromium'?require('./browser_options.cjs'):{});try{
for(const [width,height] of (process.env.AUDIT_GEOMETRY_ONLY?[]:sizes)){const ctx=await h.context(browser,{viewport:{width,height},reducedMotion:'reduce'}),p=await ctx.newPage();p.setDefaultTimeout(10000);const errors=[];p.on('pageerror',e=>errors.push(e.message));await ctx.route('**/api/**',r=>r.abort());await h.enter(p,server.url);
const scenes=await p.evaluate(()=>window.TAROT_READING_SCENARIOS);
for(const scene of scenes){await p.locator(`[data-reading=category][data-value="${scene.category}"]`).click();await fits(p,`${width} ${scene.category} catalog`);await p.locator(`[data-reading=guide][data-scenario="${scene.id}"]`).click();await fits(p,`${width} ${scene.id} intro`);await reachable(p,'[data-reading=start]',`${width} start`);await h.click(p,'guide-back');}
await p.locator('[data-reading=category][data-value=all]').click();await h.intro(p,'decision-five');await p.locator('[data-reading-option=optionA]').fill('合成选项甲');await p.locator('[data-reading-option=optionB]').fill('合成选项乙');await p.locator('[data-reading-question]').fill('这个选择有什么值得留意？');await h.click(p,'start');await fits(p,`${width} cut`);await h.toPick(p);await fits(p,`${width} pick`);await h.click(p,'fan-in');await h.click(p,'fan-out');await h.pick(p,77);await h.click(p,'pause');await h.click(p,'resume');assert.deepEqual((await h.state(p)).draft.picked,[77]);await p.reload();await p.locator('.bottomnav [data-page=reading]').click();assert.deepEqual((await h.state(p)).draft.picked,[77]);
await p.setViewportSize({width:height,height:width});await fits(p,`${width} rotate pick`);await p.setViewportSize({width,height});for(const index of [0,20,40,60])await h.pick(p,index);await p.locator('[data-reading=reveal]').waitFor();await fits(p,`${width} reveal`);await reachable(p,'[data-reading=reveal]',`${width} reveal`);await h.reveal(p);await fits(p,`${width} result`);await p.locator('[data-reading=card]').first().click();await fits(p,`${width} detail`);await h.click(p,'detail-zoom');await fits(p,`${width} zoom`);await reachable(p,'[data-reading-dialog] [data-reading=close-reference]',`${width} close detail`);await h.click(p,'close-reference');await h.click(p,'edit-question');await fits(p,`${width} edit`);await p.locator('[data-reading-edit]').fill('这个选择的下一步有什么值得留意？');await reachable(p,'[data-reading=save-question]',`${width} save`);await h.click(p,'save-question');assert.equal((await h.state(p)).draft.questionText,'这个选择的下一步有什么值得留意？');await h.click(p,'result-guide');await fits(p,`${width} result guide`);await h.click(p,'guide-back');await p.reload();await p.locator('.bottomnav [data-page=reading]').click();assert.equal(await p.locator('.reading-result-card').count(),5);await fits(p,`${width} restored result`);assert.deepEqual(errors,[]);
if([320,1720,844].includes(width))await p.screenshot({path:`/tmp/tarot-reading-audit-${name}-${width}x${height}.png`,fullPage:true});await ctx.close();console.log(`PASS ${name} reading ${width}x${height}: ${scenes.length} intros and complete local reading flow, resize/reload/modal/edit`);
}
const gc=await h.context(browser,{reducedMotion:'reduce'}),gp=await gc.newPage();await gc.route('**/api/**',r=>r.abort());await gp.addInitScript(()=>{let factory;Object.defineProperty(window,'createTarotReading',{configurable:true,get:()=>factory,set:fn=>{factory=function(...args){const instance=fn(...args);window.__responsiveReading=instance;window.__responsiveRender=()=>args[0].go('reading');return instance;};}});});await h.enter(gp,server.url);const catalog=await gp.evaluate(()=>({spreads:window.TAROT_SPREAD_CONTENT.spreads.filter(s=>!s.legacy),pool:window.TAROT_READING_DECK.cards.map(c=>({id:c.id,reversed:false}))}));
for(const [width,height] of sizes){await gp.setViewportSize({width,height});for(const spread of catalog.spreads){for(const phase of ['pick','reveal','read']){const picked=phase==='pick'?[]:spread.positions.map((_,i)=>i),draft={id:'synthetic-responsive',at:Date.now(),spreadId:spread.id,topic:'general',questionText:'',pool:catalog.pool,picked,revealed:phase==='read'?picked:[],phase};const fixture={version:1,settings:{topic:'general',spreadId:spread.id},draft,history:[],practice:[],daily:[],ui:{view:'table'}};await gp.evaluate(f=>{window.__responsiveReading.restore(f);window.__responsiveRender();},fixture);await fits(gp,`${width} ${spread.id} ${phase}`);const selector=phase==='pick'?'.selection-board':phase==='reveal'?'.reveal-group-cards':'.reading-result-cards';assert.equal(await gp.locator(selector).count(),1,`${width} ${spread.id} ${phase} renders its board`);const violations=await gp.locator(selector).evaluateAll(boards=>boards.flatMap(board=>{const b=board.getBoundingClientRect();return [...board.querySelectorAll('.reading-card,.reveal-group-face')].flatMap(card=>{const r=card.getBoundingClientRect();return r.left<b.left-1||r.right>b.right+1||r.top<b.top-1||r.bottom>b.bottom+1?[{board:{x:b.x,y:b.y,w:b.width,h:b.height},card:{x:r.x,y:r.y,w:r.width,h:r.height}}]:[];});}));assert.deepEqual(violations,[],`${width} ${spread.id} ${phase} card containment`);if(width===320&&spread.id==='one'&&phase==='pick')await gp.screenshot({path:`/tmp/tarot-reading-audit-${name}-single-pick-320.png`});}}console.log(`PASS ${name} geometry ${width}x${height}: ${catalog.spreads.length} active spread maps at pick/reveal/read`);}await gc.close();
}finally{await browser.close();await server.close();}}
(async()=>{const engines={chromium,webkit};if(process.env.TEST_BROWSER)assert(engines[process.env.TEST_BROWSER],'TEST_BROWSER must be chromium or webkit');for(const [name,engine] of Object.entries(engines))if(!process.env.TEST_BROWSER||process.env.TEST_BROWSER===name)await audit(name,engine);})().catch(e=>{console.error(e);process.exitCode=1;});
