/* Offline references are honest; exact legacy roles and user text remain intact. */
'use strict';
const assert=require('node:assert/strict'),{api,window}=require('./reading_model_harness.cjs')();const deck=window.TAROT_READING_DECK.cards,spreads=window.TAROT_SPREAD_CONTENT.spreads;
function fixture(spread,extra={}){const r={id:'fixture-'+spread.id,at:123,spreadId:spread.id,topic:spread.topic||'general',questionId:'own',questionText:'',reversals:true,pool:deck.map((c,i)=>({id:c.id,reversed:i%2===0})),picked:spread.positions.map((_,i)=>i),revealed:spread.positions.map((_,i)=>i),phase:'read',...extra};return {version:1,settings:{topic:r.topic,spreadId:r.spreadId},draft:r,history:[r],practice:[]};}
for(const spread of spreads.filter(s=>s.id!=='daily')){api.restore(fixture(spread));const html=api.render();assert.equal((html.match(/class="[^"]*\breading-result-card\b/g)||[]).length,spread.positions.length);assert(html.includes(`reading-result-cards layout-${spread.layout}`));for(const p of spread.positions)assert(html.includes(p.label));assert(!html.includes('professional-report'));assert(!html.includes('data-learn-start'));assert(!html.includes('data-journey'));assert(html.includes('这里是各张牌的含义，不会分析你写的问题。'));assert(html.includes('data-reading-ai'));assert.equal(api.export().draft.pool.length,78);}
const custom='</span><script>window.injected=true</script>用户问题';api.restore(fixture(spreads.find(s=>s.id==='one'),{questionText:custom}));const html=api.render();assert(html.includes('&lt;script&gt;'));assert(!html.includes('<script>'));assert(html.includes('data-i18n-ignore'));
const legacy=fixture(spreads.find(s=>s.id==='choice'));delete legacy.draft.contextEnabled;delete legacy.draft.questionText;api.restore(legacy);assert.equal(api.export().draft.contextEnabled,true);assert.equal(api.export().draft.questionText,'');assert.equal(api.export().draft.picked.length,6);assert.equal(api.export().ui.view,'table','old backups without UI recover the existing table');
const interrupted=fixture(spreads.find(s=>s.id==='three'));interrupted.draft.phase='reveal';interrupted.draft.revealPending=2;api.restore(interrupted);assert.equal(api.export().draft.phase,'read');assert.equal(api.export().draft.revealPending,null);
const invalid=fixture(spreads[0]);invalid.draft.pool[1]=invalid.draft.pool[0];assert.throws(()=>api.validate(invalid));console.log('PASS: 31 current/legacy result roles and exact card counts, no fake offline AI, user escaping, no learning controls, legacy context/6-card IDs and interrupted-reveal recovery.');

const historical=fixture(spreads.find(s=>s.id==='three'));historical.settings.reversals=false;historical.draft.active=2;api.restore(historical);assert.equal(api.export().settings.reversals,false,'restore preserves the historical option');assert.equal(api.export().draft.active,2,'restore preserves historical focused index without making it active in UI');
