/* RM1.2: scenario directory, complete intros, durable input, all78 fan and result navigation. */
'use strict';
const assert=require('node:assert/strict'),{chromium}=require('playwright'),h=require('./reading_ui_harness.cjs');
(async()=>{const server=await h.server(),browser=await chromium.launch(require('./browser_options.cjs'));try{
 const ctx=await h.context(browser,{reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await h.enter(p,server.url);
 assert.equal(await p.locator('.reading-theme').count(),1);assert.equal(await p.locator('.reading-spread-choice').count(),await p.evaluate(()=>window.TAROT_READING_SCENARIOS.filter(s=>s.category==='all').length));
 assert.deepEqual(await p.locator('.reading-theme').first().locator('.reading-spread-choice').evaluateAll(es=>es.slice(0,2).map(e=>e.dataset.value)),['one','yes-no']);
 for(const cat of ['love','work','study','life']){await p.locator(`[data-reading=category][data-value=${cat}]`).click();assert.equal(await p.locator('.reading-theme').count(),1,'one category is visible at a time');assert.equal(await p.locator(`#reading-theme-${cat}`).count(),1,'category switch replaces the directory content');const counts=await p.locator('.reading-spread-choice').evaluateAll(es=>es.map(e=>Number(e.querySelector('small').textContent.match(/\d+/)?.[0])));assert.deepEqual(counts,[...counts].sort((a,b)=>a-b),'simpler spreads come first');}
 const catalog=await p.evaluate(()=>window.TAROT_SPREAD_CONTENT.spreads);assert.equal(catalog.filter(s=>s.legacy).length,19);assert.equal(catalog.filter(s=>!s.legacy).length,13);
 const scenes=await p.evaluate(()=>window.TAROT_READING_SCENARIOS);
 for(const lang of ['zh','en']){if(lang==='en')await p.locator('[data-language-toggle]').click();for(const scene of scenes){const current=await p.locator('.reading-theme').getAttribute('id');if(current!==`reading-theme-${scene.category}`)await p.locator(`[data-reading=category][data-value=${scene.category}]`).click();await p.locator(`[data-reading=guide][data-scenario="${scene.id}"]`).click();const d=catalog.find(s=>s.id===scene.spreadId);assert.equal(await p.locator('.reading-position-list>li').count(),d.positions.length);assert.equal(await p.locator('.reading-slot.active,[data-reading=guide-position],[data-reading=use-spread]').count(),0);for(const width of [320,390,1280]){await p.setViewportSize({width,height:844});await h.fit(p);}if(lang==='en')await h.english(p);await h.click(p,'guide-back');}}
 await p.locator('[data-language-toggle]').click();await p.setViewportSize({width:390,height:844});await p.locator('[data-reading=category][data-value=all]').click();await h.intro(p,'yes-no');await h.click(p,'start');assert.equal(await p.locator('[data-reading-question]:focus').count(),1,'yes-no requires a specific question');await h.click(p,'guide-back');
 await h.intro(p,'decision-five');const question='</textarea><script>window.injected=true</script>我现在换工作还是明年换？';await p.locator('[data-reading-question]').fill(question);await p.locator('[data-reading-option=optionA]').fill('现在');await p.locator('[data-reading-option=optionB]').fill('明年');await h.click(p,'guide-back');await h.intro(p,'decision-five');assert.equal(await p.locator('[data-reading-question]').inputValue(),question);assert.equal(await p.locator('[data-reading-option=optionB]').inputValue(),'明年');await h.click(p,'start');await h.toPick(p,26);const before=(await h.state(p)).draft;assert.equal(before.reversals,true);assert.equal(await p.locator('[data-deck-card]').count(),78);assert.equal(await p.locator('[data-fan-viewport] img,[data-reading=pick-confirm],[data-reading=pick-page]').count(),0);
 await h.pick(p,77);await p.locator('.tray-card .reading-back').evaluate(e=>window.__placed=e);await h.pick(p,0);assert(await p.locator('.tray-card .reading-back').first().evaluate(e=>e===window.__placed),'placed card remains same node');await h.click(p,'undo');assert.deepEqual((await h.state(p)).draft.picked,[77]);
 await h.click(p,'pause');await h.click(p,'resume');assert.deepEqual((await h.state(p)).draft.picked,[77]);for(const i of [0,39,23,60])await h.pick(p,i);await h.reveal(p);let saved=(await h.state(p)).draft;assert.deepEqual(saved.pool,before.pool);assert.equal((await h.state(p)).history.length,1,'completion auto-saves');assert.equal(await p.locator('.reading-result-card').count(),5);assert.equal(await p.evaluate(()=>window.injected),undefined);assert.equal(await p.locator('.reading-interpretation,[data-reading-setting=reversals]').count(),0);
 await p.locator('.reading-header').evaluate(e=>window.__header=e);await p.locator('[data-reading=card][data-index="0"]').first().click();assert(await p.locator('[data-reading-dialog]').evaluate(e=>e.open));assert.equal(await p.locator('[data-reading-dialog] [data-journey],[data-reading-dialog] [data-academy]').count(),0);await h.click(p,'detail-zoom');const image=p.locator('.reading-detail-portrait img');await image.evaluate(e=>e.decode());const b=await image.boundingBox();assert(b.width>=140&&b.height>=220);await h.click(p,'close-reference');assert(await p.locator('.reading-header').evaluate(e=>e===window.__header));
 await p.locator('[data-reading=result-guide]').scrollIntoViewIfNeeded();const y=await p.evaluate(()=>scrollY);await h.click(p,'result-guide');assert.equal(await p.locator('.reading-position-list>li').count(),5);await h.click(p,'guide-back');await p.waitForTimeout(100);assert(Math.abs(await p.evaluate(()=>scrollY)-y)<3,'guide returns to original result position');
 await p.reload();await p.locator('.bottomnav [data-page=reading]').click();assert.deepEqual((await h.state(p)).draft.pool,saved.pool);assert.equal(await p.locator('.reading-result-card').count(),5);assert.deepEqual(errors,[]);await ctx.close();
 const historyContext=await h.context(browser,{reducedMotion:'reduce',acceptDownloads:true}),hp=await historyContext.newPage();const records=Array.from({length:40},(_,i)=>({...structuredClone(saved),id:'synthetic-history-'+i,spreadId:'one',scenarioId:'sc01',questionText:'Synthetic history '+i,userQuestion:'Synthetic history '+i,picked:[0],revealed:[0],phase:'read'}));const historyFixture={version:1,settings:{topic:'general',spreadId:'one'},draft:records[39],history:records,practice:[],daily:[],ui:{view:'gallery',historyOpen:true}};await historyContext.addInitScript(({KEY,fixture})=>localStorage.setItem(KEY,JSON.stringify(fixture)),{KEY:h.KEY,fixture:historyFixture});await h.enter(hp,server.url);const learningBefore=await hp.evaluate(()=>[localStorage.getItem('tarot-pocket-demo-v1'),localStorage.getItem('tarot-learning-units-v2')]);
 await hp.locator('[data-reading=delete-history][data-value=synthetic-history-0]').click();assert(await hp.locator('[data-reading-delete-dialog]').evaluate(e=>e.open));await h.click(hp,'cancel-delete-history');assert.equal((await h.state(hp)).history.length,40,'cancel never removes a record');await hp.locator('[data-reading=delete-history][data-value=synthetic-history-0]').click();const download=hp.waitForEvent('download');await hp.locator('[data-reading-delete-dialog] [data-action=export]').click();const backup=JSON.parse(require('node:fs').readFileSync(await (await download).path(),'utf8'));assert.equal(backup.reading.history.length,40,'backup includes every record before deletion');await h.click(hp,'confirm-delete-history');assert.deepEqual((await h.state(hp)).history.map(r=>r.id),records.slice(1).map(r=>r.id),'only the specifically confirmed reading is removed');assert.equal((await h.state(hp)).draft.id,records[39].id);assert.deepEqual(await hp.evaluate(()=>[localStorage.getItem('tarot-pocket-demo-v1'),localStorage.getItem('tarot-learning-units-v2')]),learningBefore,'deleting reading history never modifies learning');await hp.locator('[data-reading=delete-history][data-value=synthetic-history-39]').click();assert((await hp.locator('[data-reading-delete-dialog]').innerText()).includes('当前牌桌'));await h.click(hp,'confirm-delete-history');assert.equal((await h.state(hp)).draft,null,'confirmed deletion of the current saved reading closes its matching table');assert.equal((await h.state(hp)).history.length,38);await h.start(hp,'one');await hp.locator('[data-reading=cut][data-index="0"]').waitFor();assert.equal((await h.state(hp)).draft.phase,'cut','new reading works again after freeing a history slot');await historyContext.close();
 console.log('PASS: RM1.2 25 scenarios, 13 active/19 legacy structures, all intros bilingual at 320/390/1280, no first-card selection, persistent inputs, yes/no question, all78 one-tap fan, undo, exact DOM/scroll return, auto-save, reload,40-record export/cancel/specific deletion and unchanged learning.');
 }finally{await browser.close();await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
