/* Isolated learner journeys: no personal storage, provider calls, or credentials. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),context={window:{}};
for(const file of ['reading-deck.js','curriculum-content.js','journey.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),context);
const api=context.window.TarotJourney,deck=Object.fromEntries(context.window.TAROT_READING_DECK.cards.map(x=>[x.id,x])),lessons=context.window.TAROT_CURRICULUM.cards;
let variants=0;
for(const c of Object.values(deck))for(const topic of ['career','love','study'])for(const position of ['state','tension','advice']){
 const l=lessons.find(x=>x.id===c.id),s={topic,position,playVersion:3,variant:0};
 const link=api.makeStep('meaning',c,l,deck,s),match=api.makeStep('compare',c,l,deck,s);
 assert.equal(link.kind,'link');assert.equal(link.evidence.length,3);assert.equal(link.options.length,4);
 assert.equal(link.evidence.find(x=>x.id==='yes').text,c.observation);assert.equal(link.options.find(x=>x.id==='yes').text,c.core);
 assert.equal(match.kind,'match');assert.equal(match.pairs.length,2);assert.equal(new Set(match.pairs.map(x=>x.text)).size,2);
 for(const p of match.pairs)assert.equal(p.text,deck[p.id].core);
 for(const legacy of [undefined,2]){const old=api.makeStep('meaning',c,l,deck,{...s,playVersion:legacy});assert.equal(old.kind,undefined);assert.equal(old.options.find(x=>x.id==='yes').text,c.core);}
 variants++;
}
const key='tarot-pocket-demo-v1',read=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)).journey,key),session=async p=>(await read(p)).session;
async function noChinese(p){const missing=await p.evaluate(()=>{const out=[],w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);for(let n=w.nextNode();n;n=w.nextNode())if(!n.parentElement.closest('script,style,noscript,[data-i18n-ignore]')&&/[\u3400-\u9fff]/.test(n.textContent))out.push(n.textContent.trim());return [...new Set(out)];});assert.deepEqual(missing,[]);}
async function openLesson(p,id){await p.locator('[data-action=nav][data-page=home]').first().click();await p.locator('.bottomnav [data-page=library]').click();await p.locator('[data-action=filter][data-value=全部]').click();await p.locator(`.library-card[data-id=${id}]`).click();await p.locator(`[data-journey=start][data-id=${id}]`).click();}
async function solve(p){let limit=15;while(!(await session(p)).complete&&limit--){const s=await session(p),k=s.steps[s.index];
 if(k==='intro'){if(s.playVersion===3&&!s.inspected)await p.locator('[data-journey=inspect]').click();await p.locator('[data-journey=next]').click();continue;}
 if(!s.answers[k]){
 if(k==='recall'){await p.locator('[data-journey=reveal]').click();await p.locator('[data-journey=rate][data-value="4"]').click();}
 else if(s.playVersion===3&&k==='meaning'){await p.locator('[data-journey=pick-evidence][data-value=yes]').click();await p.locator('[data-journey=pick-meaning][data-value=yes]').click();await p.locator('[data-journey=check-link]').click();}
 else if(s.playVersion===3&&k==='compare'){const ids=await p.locator('[data-journey=match-card]').evaluateAll(es=>es.map(e=>e.dataset.value));for(const id of ids){await p.locator(`[data-journey=hold-meaning][data-value=${id}]`).click();await p.locator(`[data-journey=match-card][data-value=${id}]`).click();}await p.locator('[data-journey=check-link]').click();}
 else await p.locator(`[data-journey=answer][data-value="${k==='compare'?s.cardId:k==='application'?s.position:'yes'}"]`).click();
 }
 await p.locator('[data-journey=next]').click();
 }assert((await session(p)).complete);
}
(async()=>{
 let server;const external=process.env.DEMO_URL;
 if(!external){server=http.createServer((req,res)=>{let name=new URL(req.url,'http://localhost').pathname;if(name==='/')name='/index.html';const filename=path.resolve(root,'.'+name);if(!filename.startsWith(root+path.sep)||/^\/(server|node_modules|\.)/.test(name)||!(/\.(html|js|css|webp|svg|json|webmanifest)$/.test(name))){res.writeHead(403);res.end();return;}try{let data;if(name==='/locales/en.js'){const d=Object.assign({},...fs.readdirSync(path.join(root,'locales')).filter(x=>/^en-.*\.json$/.test(x)).sort().map(x=>JSON.parse(fs.readFileSync(path.join(root,'locales',x),'utf8'))));data='window.TAROT_EN='+JSON.stringify(d);}else data=fs.readFileSync(filename);res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.webp')?'image/webp':name.endsWith('.svg')?'image/svg+xml':'text/html');res.end(data);}catch(_){res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));}
 const browser=await chromium.launch(require('./browser_options.cjs'));
 try{const browserContext=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),p=await browserContext.newPage();p.setDefaultTimeout(15000);const errors=[];p.on('pageerror',e=>errors.push(e.message));const url=external||`http://127.0.0.1:${server.address().port}/`;await p.goto(url);await p.locator('[data-home-choice][data-journey=continue]').click();
 const first=(await session(p)).cardId;assert.equal((await session(p)).playVersion,3);await p.locator('.journey-discovery img').evaluate(i=>i.decode());const frame=await p.locator('.journey-discovery').evaluate(e=>{const face=e.querySelector('img').getBoundingClientRect(),caption=e.querySelector('.journey-discovery-caption').getBoundingClientRect();return {cardMiddle:face.left+face.width/2,screenMiddle:innerWidth/2,cardBottom:face.bottom,captionTop:caption.top};});assert(Math.abs(frame.cardMiddle-frame.screenMiddle)<5,'first card is centered on mobile');assert(frame.captionTop>frame.cardBottom,JSON.stringify(frame));if(process.env.LEARNING_V13_SCREENSHOTS)await p.screenshot({path:path.join(process.env.LEARNING_V13_SCREENSHOTS,'learning-v13-discovery.png'),fullPage:true});assert.equal(await p.locator('[data-journey=next]').count(),0);await p.waitForTimeout(700);assert.equal((await session(p)).index,0,'observation never auto-advances');
 assert.equal(await p.locator('.journey-discovery .journey-image').evaluate(e=>getComputedStyle(e).animationName),'none');await p.emulateMedia({reducedMotion:'no-preference'});assert.equal(await p.locator('.journey-discovery .journey-image').evaluate(e=>getComputedStyle(e).animationName),'learning-discover');await p.emulateMedia({reducedMotion:'reduce'});
 await p.locator('[data-journey=inspect]').click();assert((await session(p)).inspected);await p.locator('[data-journey=next]').click();await p.locator('[data-journey=answer][data-value=yes]').click();await p.locator('[data-journey=next]').click();
 assert.equal(await p.locator('[data-construction=link]').count(),1);if(process.env.LEARNING_V13_SCREENSHOTS)await p.screenshot({path:path.join(process.env.LEARNING_V13_SCREENSHOTS,'learning-v13-link.png'),fullPage:true});assert(await p.locator('[data-journey=check-link]').isDisabled());await p.locator('[data-journey=pick-evidence]:not([data-value=yes])').first().click();await p.locator('[data-journey=pick-meaning][data-value=yes]').click();let saved=await session(p);
 await p.reload();await p.locator('[data-home-choice][data-journey=continue]').click();assert.deepEqual((await session(p)).activity.evidence,saved.activity.evidence,'partial evidence link survives restart');assert.equal(Object.keys((await session(p)).answers).length,1,'choosing parts is not grading');
 await p.locator('[data-journey=check-link]').evaluate(b=>{b.click();b.click();});assert.match(await p.locator('.journey-feedback>strong').innerText(),/答错/);assert.match(await p.locator('.journey-feedback').innerText(),/含义选对了/);assert.equal((await read(p)).cards[first].skills.meaning.grade,2);saved=await read(p);
 await p.locator('[data-journey=retry-link]').click();await p.locator('[data-journey=pick-evidence][data-value=yes]').click();await p.locator('[data-journey=pick-meaning][data-value=yes]').click();await p.locator('[data-journey=check-link]').click();assert.match(await p.locator('.journey-feedback>strong').innerText(),/这次连对了/);assert.deepEqual((await read(p)).cards,saved.cards,'repair never rewrites the first grade or grows the interval');await p.locator('[data-journey=next]').click();await p.locator('[data-journey=reveal]').click();await p.locator('[data-journey=rate][data-value="4"]').click();await p.locator('[data-journey=next]').click();
 assert.equal(await p.locator('[data-construction=match]').count(),1);if(process.env.LEARNING_V13_SCREENSHOTS)await p.screenshot({path:path.join(process.env.LEARNING_V13_SCREENSHOTS,'learning-v13-match.png'),fullPage:true});const ids=await p.locator('[data-journey=match-card]').evaluateAll(es=>es.map(e=>e.dataset.value));await p.locator(`[data-journey=hold-meaning][data-value=${ids[0]}]`).click();await p.locator(`[data-journey=match-card][data-value=${ids[1]}]`).click();assert((await session(p)).activity.pairs[ids[1]]===ids[0]);await p.reload();await p.locator('[data-home-choice][data-journey=continue]').click();assert((await session(p)).activity.pairs[ids[1]]===ids[0],'partial pairing survives restart');await p.locator(`[data-journey=match-card][data-value=${ids[1]}]`).click();assert.equal(Object.keys((await session(p)).activity.pairs).length,0,'placed meaning can be taken back');
 for(const width of [320,390,430,1280]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'pairing fits phones and desktop');}await p.setViewportSize({width:390,height:844});
 await p.locator('[data-language-toggle]').click();await noChinese(p);await solve(p);await noChinese(p);await p.locator('[data-journey=next-card]').click();assert.notEqual((await session(p)).cardId,first,'next card is new, not the same fixed lesson');await noChinese(p);
 // Saved v1 and v2 runs must keep their original one-tap question meanings.
 for(const version of [1,2]){await p.addInitScript(({key,version})=>{const d=JSON.parse(localStorage.getItem(key)),s=d.journey.session;s.playVersion=version===1?undefined:2;s.index=0;s.answers={};s.inspected=undefined;s.activity=undefined;localStorage.setItem(key,JSON.stringify(d));},{key,version});await p.reload();await p.locator('[data-home-choice][data-journey=continue]').click();assert.equal(await p.locator('[data-journey=inspect]').count(),0);assert.equal(await p.locator('[data-journey=next]').count(),1);await solve(p);await p.locator('[data-journey=next-card]').click();}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',variants,checks:['78 evidence links and pairs in nine contexts','self-paced first look','ungraded selections persist','partial pairing undo and restore','double submit idempotence','evidence-specific incorrect feedback','repair preserves first score and interval','v1/v2 saved sessions','new card continuation','bilingual','320-1280 layout','reduced motion']}));await browserContext.close();
 }finally{await browser.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}}
})().catch(e=>{console.error(e);process.exitCode=1;});
