/* Regression for learner choice, visible foundations and uninterrupted card reference. */
const assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require('playwright');
const url=process.env.DEMO_URL||'file://'+path.resolve(__dirname,'../demo/tarot-demo.html');
const fit=p=>p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1);
(async()=>{const browser=await chromium.launch(require('./browser_options.cjs'));try{
 const ctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);
 await p.locator('[data-action=choose-cards]').click();await p.locator('[data-action=filter][data-value=收藏]').click();assert.equal(await p.evaluate(()=>document.activeElement.dataset.value),'收藏');await p.locator('[data-action=filter][data-value=全部]').click();assert.equal(await p.locator('.library-card').count(),78);
 await p.locator('[data-library-search]').fill('圣杯');const search=await p.locator('[data-library-search]').elementHandle();await p.locator('[data-library-search]').fill('圣杯七');assert.equal(await p.locator('.library-card').count(),1);assert(await search.evaluate(e=>e===document.activeElement),'search input must retain its node and focus');await p.locator('[data-library-search]').fill('');
 await p.locator('.library-card[data-id=p04]').scrollIntoViewIfNeeded();const pageY=await p.evaluate(()=>scrollY);await p.locator('.library-card[data-id=p04]').click();
 const sheet=await p.locator('#overlay .sheet').elementHandle();const extras=p.locator('#overlay details').filter({has:p.locator('[data-action=learn-card]')});await extras.locator('summary').click();
 for(const action of ['face','detail-position','save','learn-card']){
   const button=action==='face'?p.locator('[data-action=face][data-value=reversed]'):action==='detail-position'?p.locator('[data-action=detail-position][data-value=advice]'):p.locator(`[data-action=${action}]`);
   await button.scrollIntoViewIfNeeded();const y=await sheet.evaluate(e=>e.scrollTop);await button.click();assert(await sheet.evaluate(e=>e===document.querySelector('#overlay .sheet')),'detail actions keep the same sheet');assert.equal(await extras.getAttribute('open'),'','expanded reference stays open');assert(Math.abs(await sheet.evaluate(e=>e.scrollTop)-y)<2,action+' must not reset scroll');
 }
 await p.locator('.knowledge-card-links [data-action=card]').click();await p.locator('.knowledge-card-links [data-action=card][data-id=p04]').click();await p.locator('[data-action=save]').click();await p.locator('[data-action=card-back]').click();await p.locator('[data-action=card-back]').click();assert.equal(await p.locator('[data-action=save]').getAttribute('aria-pressed'),'false','returning sheet reflects favorite changed in nested reference');
 await p.locator('[data-action=zoom]').scrollIntoViewIfNeeded();const zoomY=await sheet.evaluate(e=>e.scrollTop);await p.locator('[data-action=zoom]').click();await p.keyboard.press('Escape');assert(await sheet.evaluate(e=>e===document.querySelector('#overlay .sheet')),'zoom returns to exact sheet');assert.equal(await sheet.evaluate(e=>e.scrollTop),zoomY);
 await p.locator('#overlay [data-action=close]').first().click();assert(Math.abs(await p.evaluate(()=>scrollY)-pageY)<2,'close returns to same library scroll');
 await p.locator('[data-action=library-view][data-value=foundations]').click();assert.equal(await p.evaluate(()=>document.activeElement.dataset.value),'foundations');await p.locator('[data-action=knowledge][data-value=numbers]').click();assert.equal(await p.locator('.number-family img').count(),4);
 await p.locator('[data-action=number-family][data-value="8"]').click();assert.deepEqual(await p.locator('.number-family img').evaluateAll(xs=>xs.map(x=>x.alt)),['权杖八','圣杯八','宝剑八','星币八']);const knowledge=await p.locator('#overlay .sheet').elementHandle();await p.locator('.number-family [data-action=card]').first().click();await p.locator('[data-action=card-back]').click();assert(await knowledge.evaluate(e=>e===document.querySelector('#overlay .sheet')),'card reference returns to the number comparison without rebuilding');await p.locator('#overlay [data-action=close]').first().click();
 await p.locator('[data-action=knowledge][data-value=elements]').click();assert.equal(await p.locator('.element-card img').count(),4);await p.locator('#overlay [data-action=close]').first().click();
 await p.locator('[data-action=library-view][data-value=spreads]').click();assert.equal(await p.locator('.library-spread-lessons>button').count(),3);await p.locator('[data-action=spread][data-id=three]').click();assert.equal(await p.locator('.spread-slot img').count(),3);assert.equal(await p.locator('[data-reading]').count(),0,'worked learning example does not enter live reading');await p.locator('[data-action=position][data-index="2"]').click();assert.match(await p.locator('.position-panel').first().innerText(),/建议/);
 await p.locator('.bottomnav [data-page=reading]').click();await p.locator('[data-reading=guide][data-value=three]').click();await p.locator('[data-reading=use-spread][data-value=three]').click();await p.locator('[data-reading=start]').click();await p.locator('[data-reading=skip-animation]').click();await p.locator('[data-reading=cut-default]').click();await p.locator('[data-reading=skip-animation]').click();for(let i=0;i<3;i++){await p.locator(`[data-reading=pick][data-index="${i}"]`).click();}await p.locator('[data-reading=reveal-all]').click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('tarot-reading-v3')).draft.phase==='read');
 await p.locator('[data-reading=card][data-index="0"]').click();await p.locator('[data-action=card]').first().click();assert.equal(await p.locator('#overlay [data-journey]').count(),0,'reading reference has no teaching task');assert.equal(await p.locator('#overlay [data-action=learn-card]').count(),0);await p.locator('#overlay [data-action=close]').first().click();
 for(const w of [320,390,430,1280]){await p.setViewportSize({width:w,height:844});assert(await fit(p));}
 await p.locator('[data-reading=pause]').first().click();await p.locator('.bottomnav [data-page=library]').click();await p.locator('[data-action=library-view][data-value=foundations]').click();await p.locator('[data-language-toggle]').click();await p.locator('[data-action=knowledge][data-value=numbers]').click();assert(!/[\u3400-\u9fff]/.test(await p.locator('#overlay').innerText()),'number comparison fully translated');assert.deepEqual(errors,[]);
 console.log(JSON.stringify({status:'PASS',checks:['78 selectable cards','live search preserves focus','card detail DOM and scroll retained','favorite and read markers do not reset reference','zoom and nested comparison return exactly','real four-suit numbers and elements','visible worked spreads separated from reading','reading-only card reference','bilingual foundations','responsive 320–1280']}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
