/* Continuous fan: real touch pan, pinch, one tap, keyboard and stable remaining order. */
'use strict';
const assert=require('node:assert/strict'),{chromium,webkit}=require('playwright'),h=require('./reading_ui_harness.cjs');
(async()=>{const server=await h.server();try{for(const [name,engine]of [['chromium',chromium],['webkit',webkit]]){const browser=await engine.launch(name==='chromium'?require('./browser_options.cjs'):{headless:true});try{for(const width of [320,390])for(const reducedMotion of ['no-preference','reduce']){const ctx=await h.context(browser,{viewport:{width,height:844},isMobile:true,reducedMotion}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await h.enter(p,server.url);await h.start(p);await h.toPick(p);const pool=(await h.state(p)).draft.pool;assert.equal(await p.locator('[data-deck-card]').count(),78);assert.equal(await p.locator('[data-reading=pick]:enabled').count(),78);assert.equal(await p.locator('[data-fan-viewport] img,[data-reading=pick-confirm],[data-reading=pick-page]').count(),0);await h.fit(p);
 // Every numbered card can be centered at a readable 44px+ touch size.
 for(const index of [0,20,39,59,77]){const c=await h.center(p,index);const r=await c.boundingBox(),v=await p.locator('[data-fan-viewport]').boundingBox();assert(r.width>=44&&r.height>=44);assert(r.x>=v.x-1&&r.x+r.width<=v.x+v.width+1);assert(await c.evaluate(e=>{const r=e.getBoundingClientRect();return e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),'center card not obscured');}
 if(name==='chromium'&&width===390&&reducedMotion==='no-preference'){await h.center(p,30);const b=await p.locator('[data-fan-viewport]').boundingBox(),cdp=await ctx.newCDPSession(p),x=b.x+b.width*.72,y=b.y+100;const before=await p.locator('[data-fan-viewport]').evaluate(e=>e.scrollLeft);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=9;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-i*15,y}]});await p.waitForTimeout(20);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(400);assert((await p.locator('[data-fan-viewport]').evaluate(e=>e.scrollLeft))>before+40,'native horizontal finger pan moves fan');assert.deepEqual((await h.state(p)).draft.picked,[]);const zoomBefore=(await h.state(p)).draft.fanZoom;const mid=b.x+b.width/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:mid-35,y},{x:mid+35,y}]});for(let i=1;i<=4;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:mid-35-i*8,y},{x:mid+35+i*8,y}]});await p.waitForTimeout(30);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(550);assert((await h.state(p)).draft.fanZoom>zoomBefore,'two-finger pinch enlarges fan');assert.deepEqual((await h.state(p)).draft.picked,[],'pinch never selects');await cdp.detach();}
 await p.locator('[data-reading=pick][data-index="20"]').evaluate(el=>{el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:10,clientY:10}));el.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:50,clientY:10}));el.dispatchEvent(new PointerEvent('pointercancel',{bubbles:true}));el.click();});assert.deepEqual((await h.state(p)).draft.picked,[]);await p.waitForTimeout(350);
 const z=(await h.state(p)).draft.fanZoom;await h.click(p,'fan-out');assert((await h.state(p)).draft.fanZoom<z);const smaller=(await h.state(p)).draft.fanZoom;await h.click(p,'fan-in');assert((await h.state(p)).draft.fanZoom>smaller);
 await h.center(p,77);await p.locator('.reading-fan-track').evaluate(e=>{window.__track=e;window.__cards=[...e.children];window.__scroll=e.parentElement.scrollLeft;});await p.locator('[data-reading=pick][data-index="77"]').tap();assert.deepEqual((await h.state(p)).draft.picked,[77]);assert(await p.locator('.reading-fan-track').evaluate(e=>e===window.__track&&[...e.children].every((c,i)=>c===window.__cards[i])));assert(await p.locator('[data-fan-viewport]').evaluate(e=>Math.abs(e.scrollLeft-window.__scroll)<2));assert(await p.locator('[data-reading=pick][data-index="77"]').isDisabled());await p.locator('[data-reading=pick][data-index="77"]').evaluate(e=>e.click());assert.deepEqual((await h.state(p)).draft.picked,[77]);await p.locator('.selection-board .reading-slot.filled .reading-back').evaluate(e=>window.__placed=e);
 await h.center(p,0);await p.locator('[data-reading=pick][data-index="0"]').focus();await p.keyboard.press('Enter');assert.deepEqual((await h.state(p)).draft.picked,[77,0]);assert(await p.locator('.selection-board .reading-slot.filled .reading-back').first().evaluate(e=>e===window.__placed));await h.click(p,'pause');await h.click(p,'resume');await p.reload();await p.locator('.bottomnav [data-page=reading]').click();assert.deepEqual((await h.state(p)).draft.picked,[77,0]);assert.deepEqual((await h.state(p)).draft.pool,pool);assert.equal(await p.locator('[data-reading=pick]:disabled').count(),2);
 // A late restored/layout scroll is not part of the next deliberate tap. Trigger
 // a real scroll event, then make exactly one real click without a settling delay.
 const last=await h.center(p,39);await p.locator('[data-fan-viewport]').evaluate(el=>new Promise(resolve=>{el.addEventListener('scroll',()=>resolve(),{once:true});el.scrollLeft+=1;}));await last.click();assert.deepEqual((await h.state(p)).draft.picked,[77,0,39],'one fresh tap after restored scroll picks the intended card');assert.equal((await h.state(p)).draft.phase,'reveal');assert.deepEqual(errors,[]);await ctx.close();console.log(`PASS fan ${name} ${width} ${reducedMotion}`);}}finally{await browser.close();}}}finally{await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
