/* One continuous table: automatic shuffle, one cut, selection and group reveal. */
'use strict';
const assert=require('node:assert/strict'),{chromium}=require('playwright'),h=require('./reading_ui_harness.cjs');
(async()=>{const server=await h.server(),browser=await chromium.launch(require('./browser_options.cjs'));try{
 const ctx=await h.context(browser,{reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await h.enter(p,server.url);await h.start(p);
 const raw=await h.state(p);await p.locator('[data-reading=cut][data-index="52"]').waitFor();assert.equal(await p.locator('[data-reading=motion-pause],[data-reading=motion-replay],[data-reading=skip-animation]').count(),0);
 await p.locator('[data-reading=cut][data-index="52"]').click();const cut=await h.state(p);assert.deepEqual(cut.draft.pool,[...raw.draft.pool.slice(52),...raw.draft.pool.slice(0,52)]);await p.locator('[data-fan-viewport]').waitFor();assert.equal((await h.state(p)).draft.phase,'pick');
 for(const i of [77,0,1])await h.pick(p,i);await p.locator('[data-reading=reveal]').waitFor();await h.click(p,'reveal');await p.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).draft.phase==='read',h.KEY);const normal=await h.state(p);assert.equal(await p.locator('.reading-result-card').count(),3);
 const fast=await h.context(browser,{viewport:{width:320,height:740},reducedMotion:'reduce'});await fast.addInitScript(({KEY,raw})=>localStorage.setItem(KEY,JSON.stringify(raw)),{KEY:h.KEY,raw});const q=await fast.newPage();await h.enter(q,server.url);await h.toPick(q,52);for(const i of [77,0,1])await h.pick(q,i);await h.reveal(q);assert.deepEqual((await h.state(q)).draft.pool,normal.draft.pool);assert.deepEqual((await h.state(q)).draft.picked,normal.draft.picked);await fast.close();
 await h.click(p,'pause');await h.start(p,'celtic');await h.toPick(p);for(let i=0;i<10;i++)await h.pick(p,i);await h.click(p,'reveal');await p.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).draft.phase==='read',h.KEY);assert.equal(await p.locator('.reading-result-cards.layout-celtic .reading-result-card').count(),10);assert.deepEqual(errors,[]);await ctx.close();console.log('PASS: automatic shuffle/cut, single continuous table, reduced-motion equivalence and Celtic result.');
}finally{await browser.close();await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
