/* Verify moving cards, reachable exits, scenario navigation, and local-date persistence. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),KEY='tarot-reading-v3';
const get=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY),click=(p,a,v)=>p.locator(`[data-reading="${a}"]${v?`[data-value="${v}"]`:''}`).first().click();
(async()=>{let server,url=process.env.DEMO_URL;
 if(!url){server=require('node:http').createServer((req,res)=>{const file=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html';if(file==='locales/en.js'){const dict=Object.assign({},...fs.readdirSync(path.join(root,'locales')).filter(x=>/^en-.*\.json$/.test(x)).sort().map(x=>JSON.parse(fs.readFileSync(path.join(root,'locales',x),'utf8'))));res.setHeader('Content-Type','text/javascript');res.end('window.TAROT_EN='+JSON.stringify(dict));return;}const full=path.join(root,file);if(!full.startsWith(root+path.sep)||!fs.existsSync(full)||!fs.statSync(full).isFile()){res.statusCode=404;res.end();return;}res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.webp':'image/webp','.svg':'image/svg+xml','.png':'image/png','.json':'application/json'})[path.extname(full)]||'application/octet-stream');fs.createReadStream(full).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${server.address().port}/index.html`;}
 const browser=await chromium.launch(require('./browser_options.cjs'));
 try{const ctx=await browser.newContext({viewport:{width:390,height:844}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.locator('.bottomnav [data-page=reading]').click();
 await click(p,'guide','three');await click(p,'use-spread','three');assert.equal(await p.locator('.context-picker').count(),0);await click(p,'start');
 const first=await get(p);await p.waitForTimeout(170);const transform1=await p.locator('.ritual-pack>.reading-back').first().evaluate(e=>getComputedStyle(e).transform);await p.waitForTimeout(300);const transform2=await p.locator('.ritual-pack>.reading-back').first().evaluate(e=>getComputedStyle(e).transform);assert.notEqual(transform1,transform2,'shuffle must visibly move over time');assert(await p.locator('[data-reading=pause]').isVisible());await p.screenshot({path:'/tmp/tarot-ritual-shuffle.png',fullPage:false});
 await click(p,'pause');assert.equal((await get(p)).ui.view,'gallery');await click(p,'resume');await click(p,'skip-animation');assert.equal((await get(p)).draft.phase,'cut');assert.deepEqual((await get(p)).draft.pool,first.draft.pool);await p.screenshot({path:'/tmp/tarot-ritual-cut.png',fullPage:false});
 await p.locator('[data-reading=cut][data-index="52"]').click();const cut=await get(p);assert.deepEqual(cut.draft.pool,[...first.draft.pool.slice(52),...first.draft.pool.slice(0,52)]);await p.waitForTimeout(80);const a=await p.locator('.cut-pile.selected').evaluate(e=>getComputedStyle(e).transform);await p.waitForTimeout(180);const b=await p.locator('.cut-pile.selected').evaluate(e=>getComputedStyle(e).transform);assert.notEqual(a,b,'cut must visibly move over time');await click(p,'pause');await p.reload();await p.locator('.bottomnav [data-page=reading]').click();assert.equal((await get(p)).ui.view,'gallery');await click(p,'resume');await p.locator('[data-reading=pick]').first().waitFor();assert.deepEqual((await get(p)).draft.pool,cut.draft.pool);assert.equal(await p.locator('.reading-slot img').count(),0);assert.equal(await p.locator('.reading-deck img').count(),0);
 await p.screenshot({path:'/tmp/tarot-ritual-fan.png',fullPage:false});for(const i of [0,3,8]){await p.locator(`[data-reading=pick][data-index="${i}"]`).click();await p.waitForTimeout(400);}for(let i=0;i<3;i++){await p.locator(`[data-reading=card][data-index="${i}"]`).click();await p.waitForTimeout(790);}assert.equal((await get(p)).draft.phase,'read');
 const heading=p.locator('.reading-sticky-head').first();await heading.evaluate(e=>e.dataset.identity='preserved');await p.locator('[data-reading=card][data-index="0"]').click();assert.equal(await heading.getAttribute('data-identity'),'preserved','card switching preserves the surrounding page');assert(await p.locator('.bottomnav').isVisible());await click(p,'finish');
 await p.emulateMedia({reducedMotion:'reduce'});await click(p,'daily');await p.locator('[data-reading=cut-default]').waitFor();await click(p,'cut-default');await p.locator('[data-reading=pick][data-index="5"]').click();await p.locator('[data-reading=card][data-index="0"]').click();await p.locator('.daily-result').waitFor();const daily=await get(p);await p.screenshot({path:'/tmp/tarot-ritual-daily.png',fullPage:false});await click(p,'finish');await click(p,'daily');assert.equal((await get(p)).draft.id,daily.draft.id);assert.deepEqual((await get(p)).draft.picked,daily.draft.picked);await click(p,'finish');
 for(const lang of ['zh','en']){if(lang==='en')await p.locator('[data-language-toggle]').click();const missing=async()=>{const han=await p.locator('body').evaluate(el=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n,out=[];while(n=walker.nextNode())if(/[\u3400-\u9fff]/.test(n.nodeValue)&&n.parentElement.checkVisibility()&&!n.parentElement.closest('[data-i18n-ignore],script,style'))out.push(n.nodeValue);return out;});if(lang==='en')assert.deepEqual(han,[]);};await missing();const spreads=await p.evaluate(()=>window.TAROT_SPREAD_CONTENT.spreads.filter(s=>s.id!=='daily'&&!s.legacy).map(s=>({id:s.id,count:s.positions.length})));for(const s of spreads){await click(p,'guide',s.id);assert.equal(await p.locator('.reading-slot').count(),s.count);for(const width of [320,390,430]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await missing();await click(p,'use-spread',s.id);await missing();await click(p,'question-back');await click(p,'guide-back');}}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks:['shuffle transform progresses','cut transform progresses','shuffle/cut exit and reload stable','visible fan accepts actual mobile clicks','read-only card switch keeps DOM','same-day daily revisit','reduced-motion complete ritual','7 sourced spread layouts in both languages at 320/390/430 widths','no visible untranslated text or page errors']}));await ctx.close();
 }finally{await browser.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}}
})().catch(e=>{console.error(e);process.exit(1)});
