/* Full current experience regression: the old v1.6 assertions follow their v1.7 replacements. */
const assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright');
const h=require('./reading_ui_harness.cjs'),KEY='tarot-reading-v3';
const state=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);
async function fits(p){assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
(async()=>{const server=await h.server(),url=server.url;const b=await chromium.launch(require('./browser_options.cjs'));try{const context=await h.context(b,{viewport:{width:390,height:844},reducedMotion:'reduce'}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.locator('.bottomnav [data-page=reading]').click();
const scenes=await p.evaluate(()=>TAROT_READING_SCENARIOS);assert.equal(scenes.length,25);assert.equal(await p.locator('.reading-theme').count(),1);const ids=await p.locator('[data-reading=guide]').evaluateAll(es=>es.map(e=>e.dataset.value));assert.deepEqual(ids.slice(0,2),['one','yes-no']);assert(ids.includes('yes-no'));
for(const category of ['love','work','study','life','all']){await p.locator(`[data-reading=category][data-value=${category}]`).click();assert.equal((await state(p)).ui.category,category);const section=p.locator('#reading-theme-'+category);assert(await section.isVisible());for(const w of [320,390,1280]){await p.setViewportSize({width:w,height:844});await fits(p);}}
await p.setViewportSize({width:390,height:844});await p.locator('[data-reading=category][data-value=all]').click();await p.locator('[data-reading=guide][data-value=open-three]').first().click();assert.equal(await p.locator('.reading-position-list li').count(),3);assert.equal(await p.locator('[data-reading=guide-position],.reading-slot.active').count(),0);assert.equal(await p.locator('.bottomnav:visible').count(),0);const question='我正在练习准备面试，接下来一个月有机会拿到工作吗？';await p.locator('[data-reading-question]').fill(question);await p.locator('[data-reading=guide-back]').click();await p.locator('[data-reading=guide][data-value=open-three]').first().click();assert.equal(await p.locator('[data-reading-question]').inputValue(),question);await p.locator('[data-reading=start]').click();await p.locator('[data-reading=cut][data-index="26"]').waitFor();await p.locator('[data-reading=cut][data-index="26"]').click();await p.locator('[data-fan-viewport]').waitFor();let d=(await state(p)).draft;const pool=d.pool;assert.equal(d.reversals,true);assert.equal(await p.locator('[data-reading=pick]:enabled').count(),78);assert.equal(await p.locator('[data-reading=pick-confirm],[data-reading=pick-page]').count(),0);
await p.reload();await p.locator('.bottomnav [data-page=reading]').click();assert.equal((await state(p)).ui.view,'table','reload restores the active table automatically');assert.equal(await p.locator('[data-reading=resume]').count(),0,'no redundant resume step on an already restored table');await p.locator('[data-fan-viewport]').waitFor();await p.locator('[data-reading=pause]').first().click();assert.equal(await p.locator('[data-reading=resume]').count(),1,'leaving the table exposes an explicit resume control');await p.locator('[data-reading=resume]').click();await p.locator('[data-fan-viewport]').waitFor();assert.deepEqual((await state(p)).draft.pool,pool);assert.equal((await state(p)).draft.questionText,question);
for(const i of [77,39,0]){await p.locator(`[data-reading=pick][data-index="${i}"]`).scrollIntoViewIfNeeded();await p.waitForTimeout(250);await p.locator(`[data-reading=pick][data-index="${i}"]`).click();await p.waitForTimeout(450);}assert.deepEqual((await state(p)).draft.picked,[77,39,0]);
const request=await p.evaluate(k=>TarotReadingAI.buildRequest(JSON.parse(localStorage.getItem(k)).draft,'zh'),KEY);assert.equal(request.question,question);assert.equal(request.spreadId,'open-three');assert.deepEqual(request.cards,[77,39,0].map(i=>pool[i]));
await p.locator('[data-reading=reveal]').click();await p.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).draft.phase==='read',KEY);d=(await state(p)).draft;assert.deepEqual(d.revealed,[0,1,2]);assert.equal((await state(p)).history.filter(x=>x.id===d.id).length,1,'result automatically saved once');
await p.locator('[data-reading=result-guide]').click();await p.locator('[data-reading=guide-back]').click();assert.equal((await state(p)).draft.id,d.id);assert.equal((await state(p)).ui.view,'table');for(const w of [320,390,1280]){await p.setViewportSize({width:w,height:844});await fits(p);}await p.locator('[data-reading=pause]').first().click();await p.locator('.bottomnav [data-page=home]').click();
await p.locator('[data-action=choose-cards]').click();await p.locator('.library-card[data-id=c10]').click();await p.locator('[data-academy=start][data-id=c10]').click();let boxes=[];for(let n=0;n<4;n++){const box=await p.locator('.academy-image-space img').first().boundingBox();boxes.push(box);assert.equal(await p.locator('.dossier-pair,[data-guided-note],.journey-control,[data-action=confidence]').count(),0);const step=await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('tarot-pocket-demo-v1')).journey.academy.session;const st=TarotAcademy.stepFor(s);return {kind:st.kind,correct:st.question?.correct};});if(step.kind==='question')await p.locator(`[data-academy=answer][data-value="${step.correct}"]`).click();await p.locator('[data-academy=next]').click();}
assert(boxes.every(x=>Math.abs(x.width-boxes[0].width)<1&&Math.abs(x.x-boxes[0].x)<1),'fixed card size and placement');assert.deepEqual(errors,[]);console.log('PASS: 25 scene entries across five category views, complete guide/no selected first position, question back/restore, 78 one-tap choices across deck, no duplicate reveal, saved result and original return, fixed learning card frame.');}finally{await b.close();await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
