/* Cross-screen audit of the public shell, reference library and modal return. */
'use strict';
const assert=require('node:assert/strict'),{chromium,webkit}=require('playwright'),h=require('./reading_ui_harness.cjs');
async function fits(page,label){
 const geometry=await page.evaluate(()=>{const panel=document.querySelector('#overlay .sheet')||document.querySelector('.shell'),r=panel.getBoundingClientRect();return {page:document.documentElement.scrollWidth<=innerWidth+1,panel:panel.scrollWidth<=panel.clientWidth+2,escaped:[...panel.querySelectorAll('button,input,h1,h2,h3,p')].filter(e=>e.checkVisibility()&&!e.closest('.chips')).filter(e=>{const b=e.getBoundingClientRect();return b.left<r.left-2||b.right>r.right+2}).slice(0,6).map(e=>e.className+':'+e.textContent.slice(0,30))};});
 assert(geometry.page&&geometry.panel&&geometry.escaped.length===0,`${label}: ${JSON.stringify(geometry)}`);
}
(async()=>{const server=await h.server();try{for(const [name,engine]of [['chromium',chromium],['webkit',webkit]]){const browser=await engine.launch(name==='chromium'?require('./browser_options.cjs'):{headless:true});try{for(const [width,height]of [[320,568],[390,844],[600,800],[768,1024],[1280,800],[1720,980],[844,390]]){const context=await h.context(browser,{viewport:{width,height},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(server.url);await fits(page,'home');if(width===320){const boxes=await page.evaluate(()=>({draw:document.querySelector('.reading-choice').getBoundingClientRect().bottom,nav:document.querySelector('.bottomnav').getBoundingClientRect().top}));assert(boxes.draw<=boxes.nav,'both primary home entries fit above navigation on a short phone');}
 await page.locator('[data-action=nav][data-page=library]').first().click();await fits(page,'library');assert.equal(await page.locator('.library-card').count(),78);
 const search=page.locator('[data-library-search]');await search.fill('星币国王');assert.equal(await page.locator('.library-card').count(),1);await page.locator('[data-action=card][data-id=p14]').click();await fits(page,'reference card');await page.locator('#overlay [data-action=face][data-value=reversed]').click();await page.locator('#overlay [data-action=save]').click();await page.locator('#overlay .sheet').evaluate(el=>el.scrollTop=120);await page.locator('#overlay [data-action=zoom]').first().scrollIntoViewIfNeeded();const before=await page.locator('#overlay .sheet').evaluate(el=>el.scrollTop);await page.locator('#overlay [data-action=zoom]').first().click();await page.keyboard.press('Escape');assert.equal(await page.locator('#overlay .sheet').evaluate(el=>el.scrollTop),before,'zoom return preserves reference scroll');assert.equal(await page.locator('#overlay [data-action=face][data-value=reversed]').getAttribute('aria-pressed'),'true');await page.keyboard.press('Escape');assert.equal(await search.inputValue(),'星币国王','reference return keeps search');await search.fill('');await page.locator('[data-action=filter][data-value=收藏]').click();assert.equal(await page.locator('.library-card').count(),1);
 await page.locator('[data-action=library-view][data-value=spreads]').click();await fits(page,'reference spread list');const all=await page.locator('[data-action=reference-spread]').evaluateAll(es=>es.map(e=>e.dataset.id));assert.equal(all.length,20);for(const id of all){await page.locator(`[data-action=reference-spread][data-id="${id}"]`).click();await fits(page,'spread '+id);await page.locator('#overlay [data-action=close]').first().click();}
 await page.locator('[data-action=nav][data-page=me]').first().click();await fits(page,'records');await page.locator('[data-action=nav][data-page=home]').first().click();await page.locator('[data-action=status]').click();await page.locator('#overlay .status-value').first().waitFor();await fits(page,'content status');assert.match(await page.locator('#overlay .status-value').first().innerText(),/78 \/ 78/);await page.keyboard.press('Escape');assert.deepEqual(errors,[]);await context.close();console.log(`PASS global ${name} ${width}x${height}: home, 78-card search/favorite/zoom return, 20 spread details, records and content status`);}}finally{await browser.close();}}}finally{await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
